import type { SiteConfig } from "./types";

const BASE = "/templates/supermarket5";

export const SUPERMARKET5_DEFAULTS: SiteConfig = {
  name: "VividMart",
  tagline: "Shop Bold, Live Fresh",
  logo: { text: "VividMart", alt: "VividMart" },
  theme: {
    primary: "#7C3AED",
    primaryFg: "#ffffff",
    accent: "#f59e0b",
    background: "#F3F4F6",
    foreground: "#1f2937",
    muted: "#6b7280",
    surface: "#ffffff",
    border: "#e5e7eb",
    radius: "sm",
  },
  contact: {
    email: "hello@vividmart.com",
    phone: "+1 (555) 567-8901",
    phone2: "+1 (555) 567-8902",
    address: "789 Vivid Blvd, Purple City, PC 50005",
    hours: "Mon–Sun 8am–9pm",
  },
  social: { facebook: "#", twitter: "#", instagram: "#", youtube: "#" },
  announcement: { text: "New arrivals every week — up to 25% off select items!", active: true },
  sections: [
    { id: "features",  label: "Features Row",      active: true },
    { id: "featured",  label: "Featured Products",  active: true },
    { id: "discount",  label: "Discount Products",  active: true },
    { id: "weekly",    label: "Weekly Best Selling", active: true },
    { id: "trending",  label: "Trending Products",  active: true },
    { id: "blog",      label: "Blog Posts",         active: true },
  ],
  categories: [
    { id:"1", handle:"breakfast-dairy",  name:"Breakfast & Dairy",   image:`${BASE}/category/01.jpg`, active:true },
    { id:"2", handle:"meats-seafood",    name:"Meats & Seafood",     image:`${BASE}/category/02.jpg`, active:true },
    { id:"3", handle:"breads-bakery",    name:"Breads & Bakery",     image:`${BASE}/category/03.jpg`, active:true },
    { id:"4", handle:"chips-snacks",     name:"Chips & Snacks",      image:`${BASE}/category/04.jpg`, active:true },
    { id:"5", handle:"organic-produce",  name:"Organic Produce",     image:`${BASE}/category/05.jpg`, active:true },
    { id:"6", handle:"beverages",        name:"Beverages",           image:`${BASE}/category/06.jpg`, active:true },
    { id:"7", handle:"frozen-foods",     name:"Frozen Foods",        image:`${BASE}/category/07.jpg`, active:true },
    { id:"8", handle:"grocery-staples",  name:"Grocery & Staples",   image:`${BASE}/category/08.jpg`, active:true },
  ],
  products: [
    { id:"1",  handle:"fresh-whole-milk",    name:"Fresh Whole Milk",          category:"breakfast-dairy",  images:[`${BASE}/products/01.jpg`], price:299,  unit:"1L",    badge:"new",     featured:true,  active:true, description:"Farm-fresh whole milk, rich and creamy." },
    { id:"2",  handle:"organic-eggs",        name:"Organic Free-Range Eggs",   category:"breakfast-dairy",  images:[`${BASE}/products/02.jpg`], price:549,  unit:"12 pack",badge:"organic", featured:true,  active:true, description:"Certified organic, free-range eggs." },
    { id:"3",  handle:"sourdough-bread",     name:"Artisan Sourdough Bread",   category:"breads-bakery",    images:[`${BASE}/products/03.jpg`], price:489,  unit:"loaf",  badge:"new",     featured:true,  active:true, description:"Hand-crafted artisan sourdough with a golden crust." },
    { id:"4",  handle:"chicken-breast",      name:"Boneless Chicken Breast",   category:"meats-seafood",    images:[`${BASE}/products/04.jpg`], price:899,  compareAtPrice:1099, unit:"kg", badge:"sale", featured:true, active:true, description:"Premium boneless, skinless chicken breast." },
    { id:"5",  handle:"atlantic-salmon",     name:"Atlantic Salmon Fillet",    category:"meats-seafood",    images:[`${BASE}/products/05.jpg`], price:1299, unit:"500g",  badge:null,      featured:false, active:true, description:"Fresh Atlantic salmon, sustainably sourced." },
    { id:"6",  handle:"mixed-nuts",          name:"Premium Mixed Nuts",        category:"chips-snacks",     images:[`${BASE}/products/06.jpg`], price:799,  compareAtPrice:999, unit:"300g", badge:"sale", featured:true, active:true, description:"A premium blend of almonds, cashews, and walnuts." },
    { id:"7",  handle:"organic-bananas",     name:"Organic Bananas",           category:"organic-produce",  images:[`${BASE}/products/07.jpg`], price:249,  unit:"bunch", badge:"organic", featured:false, active:true, description:"Sweet organic bananas, perfectly ripened." },
    { id:"8",  handle:"orange-juice",        name:"Fresh Orange Juice",        category:"beverages",        images:[`${BASE}/products/08.jpg`], price:399,  unit:"1L",    badge:"new",     featured:true,  active:true, description:"Freshly squeezed orange juice, no added sugar." },
    { id:"9",  handle:"greek-yogurt",        name:"Greek Yogurt",              category:"breakfast-dairy",  images:[`${BASE}/products/09.jpg`], price:349,  unit:"500g",  badge:null,      featured:false, active:true, description:"Thick and creamy authentic Greek yogurt." },
    { id:"10", handle:"frozen-pizza",        name:"Stone-Baked Frozen Pizza",  category:"frozen-foods",     images:[`${BASE}/products/10.jpg`], price:699,  compareAtPrice:899, unit:"each", badge:"sale", featured:true, active:true, description:"Stone-baked frozen pizza with premium toppings." },
    { id:"11", handle:"pasta-fusilli",       name:"Italian Fusilli Pasta",     category:"grocery-staples",  images:[`${BASE}/products/11.jpg`], price:199,  unit:"500g",  badge:null,      featured:false, active:true, description:"Authentic Italian fusilli pasta, bronze-die cut." },
    { id:"12", handle:"olive-oil",           name:"Extra Virgin Olive Oil",    category:"grocery-staples",  images:[`${BASE}/products/12.jpg`], price:1199, compareAtPrice:1499, unit:"750ml", badge:"sale", featured:true, active:true, description:"Cold-pressed extra virgin olive oil from Spain." },
    { id:"13", handle:"sparkling-water",     name:"Sparkling Mineral Water",   category:"beverages",        images:[`${BASE}/products/13.jpg`], price:149,  unit:"500ml", badge:null,      featured:false, active:true, description:"Naturally carbonated mineral water." },
    { id:"14", handle:"cheddar-cheese",      name:"Mature Cheddar Cheese",     category:"breakfast-dairy",  images:[`${BASE}/products/14.jpg`], price:649,  unit:"200g",  badge:"hot",     featured:true,  active:true, description:"Aged mature cheddar with a sharp, rich flavor." },
    { id:"15", handle:"sea-bass",            name:"Sea Bass Fillet",           category:"meats-seafood",    images:[`${BASE}/products/15.jpg`], price:1499, unit:"400g",  badge:null,      featured:false, active:true, description:"Delicate sea bass fillet, fresh from the ocean." },
    { id:"16", handle:"whole-wheat-crackers",name:"Whole Wheat Crackers",      category:"chips-snacks",     images:[`${BASE}/products/16.jpg`], price:299,  unit:"200g",  badge:null,      featured:false, active:true, description:"Crispy whole wheat crackers, lightly salted." },
    { id:"17", handle:"strawberries",        name:"Fresh Strawberries",        category:"organic-produce",  images:[`${BASE}/products/17.jpg`], price:449,  unit:"400g",  badge:"hot",     featured:true,  active:true, description:"Ripe, sweet strawberries picked at peak freshness." },
    { id:"18", handle:"frozen-berries",      name:"Frozen Mixed Berries",      category:"frozen-foods",     images:[`${BASE}/products/18.jpg`], price:549,  unit:"500g",  badge:null,      featured:false, active:true, description:"A vibrant mix of frozen blueberries, raspberries, and blackberries." },
    { id:"19", handle:"basmati-rice",        name:"Premium Basmati Rice",      category:"grocery-staples",  images:[`${BASE}/products/19.jpg`], price:899,  unit:"2kg",   badge:null,      featured:false, active:true, description:"Aged basmati rice with long, fluffy grains." },
    { id:"20", handle:"green-tea",           name:"Premium Green Tea",         category:"beverages",        images:[`${BASE}/products/20.jpg`], price:599,  unit:"20 bags",badge:"new",    featured:true,  active:true, description:"Premium Japanese green tea, rich in antioxidants." },
  ],
};
