import type { SiteConfig } from "./types";

const BASE = "/templates/shata-medical";

export const SHATA_MEDICAL_DEFAULTS: SiteConfig = {
  slug: "shata-medical",
  name: "Shata Medical Center",
  tagline: "Advanced Care. Human Touch.",
  description:
    "A full-service medical center providing specialist consultations, diagnostics, and surgical care with a patient-first approach.",
  locale: "en-US",

  logo: {
    text: "Shata Medical",
    alt: "Shata Medical Center",
  },

  theme: {
    primary:    "#1565c0",
    primaryFg:  "#ffffff",
    accent:     "#0288d1",
    background: "#ffffff",
    foreground: "#111827",
    muted:      "#64748b",
    surface:    "#f0f7ff",
    border:     "#d1dce8",
    radius:     "md",
  },

  contact: {
    email:          "info@shatamedical.com",
    phone:          "+1 (800) 555-0200",
    emergencyPhone: "+1 (800) 555-0911",
    address:        "1200 Health Blvd, Suite 400, New York, NY 10001",
    hours:          "Mon–Fri 8am–8pm · Sat 9am–5pm · Emergency 24/7",
  },

  social: {
    facebook:  "https://facebook.com",
    instagram: "https://instagram.com",
    twitter:   "https://twitter.com",
    youtube:   "https://youtube.com",
    linkedin:  "https://linkedin.com",
  },

  navigation: [
    { label: "Home",        href: "/templates/medical-center-1/preview" },
    { label: "Services",    href: "/templates/medical-center-1/preview/services" },
    { label: "Doctors",     href: "/templates/medical-center-1/preview/doctors" },
    { label: "About",       href: "/templates/medical-center-1/preview/about" },
    { label: "Contact",     href: "/templates/medical-center-1/preview/contact" },
  ],

  footerLinks: [
    {
      title: "Services",
      items: [
        { label: "Cardiology",   href: "/templates/medical-center-1/preview/services/cardiology" },
        { label: "Neurology",    href: "/templates/medical-center-1/preview/services/neurology" },
        { label: "Orthopedics",  href: "/templates/medical-center-1/preview/services/orthopedics" },
        { label: "Dental Care",  href: "/templates/medical-center-1/preview/services/dental-care" },
        { label: "Pediatrics",   href: "/templates/medical-center-1/preview/services/pediatrics" },
      ],
    },
    {
      title: "Quick Links",
      items: [
        { label: "Book Appointment", href: "/templates/medical-center-1/preview/appointment/request" },
        { label: "Our Doctors",      href: "/templates/medical-center-1/preview/doctors" },
        { label: "About Us",         href: "/templates/medical-center-1/preview/about" },
        { label: "Contact",          href: "/templates/medical-center-1/preview/contact" },
      ],
    },
    {
      title: "Legal",
      items: [
        { label: "Privacy Policy",    href: "#" },
        { label: "Terms of Service",  href: "#" },
        { label: "Cookie Policy",     href: "#" },
      ],
    },
  ],

  departments: [
    { id: "dept-1", handle: "cardiology",    name: "Cardiology",       icon: `${BASE}/icons/service_icon_1.png` },
    { id: "dept-2", handle: "neurology",     name: "Neurology",        icon: `${BASE}/icons/service_icon_2.png` },
    { id: "dept-3", handle: "orthopedics",   name: "Orthopedics",      icon: `${BASE}/icons/service_icon_3.png` },
    { id: "dept-4", handle: "ophthalmology", name: "Ophthalmology",    icon: `${BASE}/icons/service_icon_4.png` },
    { id: "dept-5", handle: "dental-care",   name: "Dental Care",      icon: `${BASE}/icons/service_icon_5.png` },
    { id: "dept-6", handle: "pediatrics",    name: "Pediatrics",       icon: `${BASE}/icons/service_icon_6.png` },
    { id: "dept-7", handle: "radiology",     name: "Radiology",        icon: `${BASE}/icons/service_icon_7.png` },
    { id: "dept-8", handle: "surgery",       name: "General Surgery",  icon: `${BASE}/icons/service_icon_8.png` },
  ],

  services: [
    {
      id: "svc-1",
      handle: "cardiology",
      name: "Cardiology",
      department: "Cardiology",
      category: "cardiology",
      shortDescription: "Comprehensive diagnosis and treatment of heart and vascular conditions.",
      description:
        "Our Cardiology department provides complete care for heart conditions — from preventive screenings and stress testing to interventional procedures and long-term cardiac rehabilitation. We use state-of-the-art echocardiography, Holter monitoring, and catheterization labs staffed by board-certified cardiologists.",
      duration: "30–60 min",
      priceLabel: "From $180",
      highlights: [
        "12-lead ECG & stress testing",
        "Echocardiography & Doppler",
        "Cardiac catheterization",
        "Holter monitoring (24–48 hr)",
        "Cardiac rehabilitation programs",
        "Hypertension & lipid management",
      ],
      images: [`${BASE}/services/service_bg.jpg`, `${BASE}/services/service_details_1.jpg`],
      icon: `${BASE}/icons/service_icon_1.png`,
      badge: "popular",
      featured: true,
      active: true,
    },
    {
      id: "svc-2",
      handle: "neurology",
      name: "Neurology",
      department: "Neurology",
      category: "neurology",
      shortDescription: "Expert diagnosis and management of neurological disorders.",
      description:
        "The Neurology department specialises in disorders of the brain, spine, and peripheral nervous system. Our neurologists combine clinical expertise with advanced imaging — MRI, CT, and EEG — to diagnose and treat conditions including epilepsy, stroke, multiple sclerosis, Parkinson's disease, and migraines.",
      duration: "45–90 min",
      priceLabel: "From $200",
      highlights: [
        "EEG & neurophysiology testing",
        "MRI & CT brain imaging",
        "Stroke fast-track protocol",
        "Epilepsy management",
        "Memory & dementia clinic",
        "Headache & migraine programme",
      ],
      images: [`${BASE}/services/service_bg_2.jpg`, `${BASE}/services/service_details_2.jpg`],
      icon: `${BASE}/icons/service_icon_2.png`,
      badge: "featured",
      featured: true,
      active: true,
    },
    {
      id: "svc-3",
      handle: "orthopedics",
      name: "Orthopedics",
      department: "Orthopedics",
      category: "orthopedics",
      shortDescription: "Surgical and non-surgical care for bones, joints, and muscles.",
      description:
        "Our Orthopedics team treats the full range of musculoskeletal conditions — from sports injuries and fractures to joint replacements and spinal surgery. We offer minimally invasive arthroscopy, joint preservation procedures, and dedicated physiotherapy programs to get patients moving again.",
      duration: "30–45 min",
      priceLabel: "From $150",
      highlights: [
        "Total hip & knee replacement",
        "Arthroscopic surgery",
        "Sports injury management",
        "Spinal decompression",
        "Fracture care & orthopaedics trauma",
        "Post-surgical physiotherapy",
      ],
      images: [`${BASE}/services/service_bg_3.jpg`, `${BASE}/services/service_1.png`],
      icon: `${BASE}/icons/service_icon_3.png`,
      featured: true,
      active: true,
    },
    {
      id: "svc-4",
      handle: "ophthalmology",
      name: "Ophthalmology",
      department: "Ophthalmology",
      category: "ophthalmology",
      shortDescription: "Complete eye care from routine exams to complex surgery.",
      description:
        "Our Ophthalmology clinic provides comprehensive eye health services. From routine vision assessments and prescription lenses to advanced surgical procedures including LASIK, cataract removal, and retinal surgery, our team delivers precise, personalised eye care.",
      duration: "20–45 min",
      priceLabel: "From $120",
      highlights: [
        "Comprehensive eye examination",
        "Cataract surgery",
        "LASIK & refractive surgery",
        "Retinal disease management",
        "Glaucoma screening & treatment",
        "Paediatric ophthalmology",
      ],
      images: [`${BASE}/services/service_bg_4.jpg`, `${BASE}/services/service_2.jpg`],
      icon: `${BASE}/icons/service_icon_4.png`,
      active: true,
    },
    {
      id: "svc-5",
      handle: "dental-care",
      name: "Dental Care",
      department: "Dental Care",
      category: "dental-care",
      shortDescription: "Preventive, restorative, and cosmetic dental services.",
      description:
        "Our Dental Care unit covers everything from routine cleanings and fillings to complex restorative work and cosmetic treatments. We use digital X-rays, CBCT imaging, and CAD/CAM technology to deliver precise, same-visit restorations in a comfortable environment.",
      duration: "30–60 min",
      priceLabel: "From $90",
      highlights: [
        "Preventive cleaning & check-ups",
        "Dental implants & crowns",
        "Orthodontics & Invisalign",
        "Teeth whitening",
        "Root canal treatment",
        "Paediatric dentistry",
      ],
      images: [`${BASE}/services/service_3.jpg`, `${BASE}/services/service_bg.jpg`],
      icon: `${BASE}/icons/service_icon_5.png`,
      badge: "popular",
      featured: true,
      active: true,
    },
    {
      id: "svc-6",
      handle: "pediatrics",
      name: "Pediatrics",
      department: "Pediatrics",
      category: "pediatrics",
      shortDescription: "Dedicated medical care for newborns, children, and adolescents.",
      description:
        "Our Paediatrics department provides warm, child-friendly healthcare from birth through adolescence. Services include newborn care, vaccination programmes, developmental assessments, management of acute and chronic conditions, and adolescent medicine — all delivered by paediatric specialists.",
      duration: "20–40 min",
      priceLabel: "From $100",
      highlights: [
        "Newborn & well-child checks",
        "Vaccination programme",
        "Developmental assessments",
        "Asthma & allergy management",
        "Paediatric nutrition counselling",
        "Adolescent medicine",
      ],
      images: [`${BASE}/services/service_4.jpg`, `${BASE}/services/service_bg_2.jpg`],
      icon: `${BASE}/icons/service_icon_6.png`,
      active: true,
    },
    {
      id: "svc-7",
      handle: "radiology",
      name: "Radiology",
      department: "Radiology",
      category: "radiology",
      shortDescription: "High-resolution imaging and diagnostic radiology services.",
      description:
        "Our Radiology department operates 24/7 with the latest imaging equipment — 3T MRI, 128-slice CT, digital X-ray, ultrasound, mammography, and interventional radiology suites. Reports are available within hours and can be shared digitally with referring physicians.",
      duration: "15–60 min",
      priceLabel: "From $80",
      highlights: [
        "3T MRI & open MRI",
        "128-slice CT scanning",
        "Digital X-ray & fluoroscopy",
        "Ultrasound & Doppler",
        "Mammography & DEXA scan",
        "Interventional radiology",
      ],
      images: [`${BASE}/services/service_details_1.jpg`, `${BASE}/services/service_bg_3.jpg`],
      icon: `${BASE}/icons/service_icon_7.png`,
      active: true,
    },
    {
      id: "svc-8",
      handle: "general-surgery",
      name: "General Surgery",
      department: "General Surgery",
      category: "surgery",
      shortDescription: "Minimally invasive and open surgical procedures by expert surgeons.",
      description:
        "Our General Surgery team performs a wide range of elective and emergency procedures — from laparoscopic cholecystectomy and hernia repair to colorectal and thyroid surgery. We emphasise minimal access techniques to reduce recovery time and hospital stays.",
      duration: "Varies",
      priceLabel: "From $500",
      highlights: [
        "Laparoscopic & robotic surgery",
        "Hernia repair",
        "Colorectal surgery",
        "Thyroid & parathyroid surgery",
        "Breast surgery",
        "Day-surgery & fast-track recovery",
      ],
      images: [`${BASE}/services/service_details_2.jpg`, `${BASE}/services/service_bg_4.jpg`],
      icon: `${BASE}/icons/service_icon_8.png`,
      featured: true,
      active: true,
    },
  ],

  doctors: [
    {
      id: "doc-1",
      handle: "dr-james-carter",
      name: "Dr. James Carter",
      specialty: "Cardiologist",
      department: "cardiology",
      shortBio: "Board-certified cardiologist with 18 years of interventional experience.",
      bio: "Dr. James Carter is a consultant cardiologist specialising in interventional cardiology and heart failure management. He trained at Johns Hopkins and completed a fellowship at the Cleveland Clinic. He has performed over 4,000 cardiac catheterizations and is a leading voice in preventive cardiovascular medicine.",
      image: `${BASE}/team/team_1.jpg`,
      qualifications: ["MD (Johns Hopkins)", "FACC", "FSCAI", "Fellowship – Cleveland Clinic"],
      languages: ["English", "Spanish"],
      availability: "Mon, Wed, Fri · 9am–5pm",
      featured: true,
      active: true,
    },
    {
      id: "doc-2",
      handle: "dr-sarah-mitchell",
      name: "Dr. Sarah Mitchell",
      specialty: "Neurologist",
      department: "neurology",
      shortBio: "Specialist in epilepsy and neurodegenerative disorders.",
      bio: "Dr. Sarah Mitchell is a consultant neurologist with a special interest in epilepsy and movement disorders. She completed her neurology residency at Mayo Clinic and a fellowship in epileptology at UCSF. She leads the Center's Memory and Cognitive Assessment programme.",
      image: `${BASE}/team/team_3.jpg`,
      qualifications: ["MD (Mayo Clinic)", "FAAN", "Epilepsy Fellowship – UCSF"],
      languages: ["English", "French"],
      availability: "Tue, Thu · 10am–6pm",
      featured: true,
      active: true,
    },
    {
      id: "doc-3",
      handle: "dr-robert-evans",
      name: "Dr. Robert Evans",
      specialty: "Orthopedic Surgeon",
      department: "orthopedics",
      shortBio: "Minimally invasive joint replacement and sports injury expert.",
      bio: "Dr. Robert Evans is a fellowship-trained orthopedic surgeon specialising in minimally invasive joint replacement and sports medicine. He trained at Hospital for Special Surgery in New York and has an active research program in cartilage preservation and robotic-assisted arthroplasty.",
      image: `${BASE}/team/team_4.jpg`,
      qualifications: ["MD (Columbia University)", "FAAOS", "Fellowship – Hospital for Special Surgery"],
      languages: ["English"],
      availability: "Mon–Thu · 8am–4pm",
      featured: true,
      active: true,
    },
    {
      id: "doc-4",
      handle: "dr-emily-chen",
      name: "Dr. Emily Chen",
      specialty: "Pediatrician",
      department: "pediatrics",
      shortBio: "Dedicated to children's health from infancy through adolescence.",
      bio: "Dr. Emily Chen is a board-certified pediatrician with a warm, family-centred approach to child health. A graduate of Harvard Medical School, she completed her residency at Boston Children's Hospital. She has particular expertise in childhood developmental concerns and adolescent nutrition.",
      image: `${BASE}/team/team_5.jpg`,
      qualifications: ["MD (Harvard Medical School)", "FAAP", "Residency – Boston Children's Hospital"],
      languages: ["English", "Mandarin"],
      availability: "Mon–Fri · 9am–5pm",
      featured: true,
      active: true,
    },
    {
      id: "doc-5",
      handle: "dr-michael-torres",
      name: "Dr. Michael Torres",
      specialty: "Ophthalmologist",
      department: "ophthalmology",
      shortBio: "LASIK and cataract surgery specialist with a focus on corneal disease.",
      bio: "Dr. Michael Torres is a board-certified ophthalmologist with advanced training in refractive and cataract surgery. He completed his cornea fellowship at Wills Eye Hospital and has performed over 8,000 refractive procedures. He is an active member of the American Academy of Ophthalmology.",
      image: `${BASE}/team/team_6.jpg`,
      qualifications: ["MD (Duke University)", "AAO Fellow", "Cornea Fellowship – Wills Eye Hospital"],
      languages: ["English", "Spanish"],
      availability: "Mon, Tue, Thu · 10am–6pm",
      active: true,
    },
    {
      id: "doc-6",
      handle: "dr-aisha-rahman",
      name: "Dr. Aisha Rahman",
      specialty: "General Surgeon",
      department: "surgery",
      shortBio: "Specialist in laparoscopic and robotic-assisted surgical procedures.",
      bio: "Dr. Aisha Rahman is a consultant general and laparoscopic surgeon with expertise in minimally invasive techniques. She trained at Oxford University Hospitals and completed a robotic surgery fellowship at the Intuitive Robotic Center. She leads the center's day-surgery programme.",
      image: `${BASE}/team/team_7.jpg`,
      qualifications: ["MBBS (Oxford)", "FRCS (Gen Surg)", "Robotic Fellowship – Intuitive Robotic Center"],
      languages: ["English", "Arabic"],
      availability: "Wed, Fri · 8am–4pm",
      active: true,
    },
  ],

  about: {
    title: "Advancing Healthcare Through Expert Care",
    subtitle:
      "For over 20 years, Shata Medical Center has delivered specialist-led, patient-first healthcare that combines advanced technology with genuine compassion.",
    story:
      "Founded in 2004, Shata Medical Center began as a single cardiology clinic and has grown into a full-service multi-specialty center. Our founder, Dr. William Shata, believed that world-class medicine should be accessible and compassionate — not cold and clinical.\n\nToday, our 200-strong team of specialists, nurses, and allied health professionals serves over 50,000 patients a year across eight departments. We invest continuously in the latest diagnostic equipment and surgical techniques, while never losing sight of what matters most: the patient in front of us.",
    mission:
      "To provide accessible, evidence-based, specialist care that improves health outcomes and enhances quality of life for every patient we serve.",
    vision:
      "To be the region's most trusted medical center — where technology and humanity work together to deliver exceptional patient experiences.",
    image: `${BASE}/about/about_img_1.jpg`,
    stats: [
      { value: "20+",  label: "Years of Excellence" },
      { value: "50K+", label: "Patients Per Year" },
      { value: "200+", label: "Medical Specialists" },
      { value: "98%",  label: "Patient Satisfaction" },
    ],
    values: [
      { title: "Patient First",     copy: "Every decision we make starts with what is best for the patient, not the institution." },
      { title: "Clinical Excellence", copy: "We hold ourselves to the highest evidence-based standards in diagnosis, treatment, and outcomes." },
      { title: "Compassionate Care",  copy: "We treat every patient with dignity, empathy, and respect — regardless of background." },
      { title: "Continuous Innovation", copy: "We adopt proven new technologies to deliver better, faster, and safer care." },
      { title: "Transparency",       copy: "We communicate clearly about diagnoses, options, and costs. No surprises." },
      { title: "Community Impact",   copy: "We run free community health screenings and support underserved populations." },
    ],
  },

  homeSectionOrder: [
    { id: "hero",              enabled: true },
    { id: "departments",       enabled: true },
    { id: "about",             enabled: true },
    { id: "stats",             enabled: true },
    { id: "featured-services", enabled: true },
    { id: "doctors",           enabled: true },
    { id: "process",           enabled: true },
    { id: "testimonials",      enabled: true },
    { id: "cta",               enabled: true },
    { id: "newsletter",        enabled: true },
  ],

  sections: {
    announcement: {
      enabled: true,
      text: "📞 Emergency line: +1 (800) 555-0911 · Open 24/7",
    },
    hero: {
      slides: [
        {
          heading: "Advanced Care.\nHuman Touch.",
          subheading:
            "Eight specialist departments. Expert physicians. State-of-the-art diagnostics — all under one roof.",
          image: `${BASE}/hero/hero_slider_1.jpg`,
          cta: { label: "Book Appointment", href: "/templates/medical-center-1/preview/appointment/request" },
          ctaSecondary: { label: "Our Services", href: "/templates/medical-center-1/preview/services" },
        },
        {
          heading: "Your Partner\nin Good Health.",
          subheading:
            "From preventive screenings to complex surgery — personalised, evidence-based care at every step.",
          image: `${BASE}/hero/hero_slider_2.jpg`,
          cta: { label: "Meet Our Doctors", href: "/templates/medical-center-1/preview/doctors" },
          ctaSecondary: { label: "About Us", href: "/templates/medical-center-1/preview/about" },
        },
        {
          heading: "Compassionate Care\nYou Can Trust.",
          subheading:
            "Over 50,000 patients trust Shata Medical every year. Experience the difference of truly patient-first care.",
          image: `${BASE}/hero/hero_slider_3.jpg`,
          cta: { label: "Book Appointment", href: "/templates/medical-center-1/preview/appointment/request" },
          ctaSecondary: { label: "Contact Us", href: "/templates/medical-center-1/preview/contact" },
        },
      ],
    },
    about: {
      eyebrow: "About Us",
      title: "Healing with Expertise and Empathy",
      body: "Since 2004, Shata Medical Center has combined specialist expertise with genuine human warmth. Our multidisciplinary teams collaborate to provide diagnoses and treatment plans that are tailored to each patient — because no two patients are the same.",
      image: `${BASE}/about/about_section_img_1.png`,
      checkpoints: [
        "Board-certified specialists in every department",
        "Same-day appointments available",
        "Advanced imaging & diagnostics on-site",
        "Multilingual patient support",
      ],
      cta: { label: "Learn More About Us", href: "/templates/medical-center-1/preview/about" },
    },
    stats: {
      backgroundImage: `${BASE}/bg/counter_bg_1.jpeg`,
      items: [
        { value: "567+",  label: "Active Patients",    icon: `${BASE}/icons/service_icon_1.png` },
        { value: "200+",  label: "Medical Specialists", icon: `${BASE}/icons/service_icon_2.png` },
        { value: "98%",   label: "Patient Satisfaction", icon: `${BASE}/icons/service_icon_3.png` },
        { value: "24/7",  label: "Emergency Care",     icon: `${BASE}/icons/service_icon_4.png` },
      ],
    },
    featuredServices: {
      eyebrow: "What We Offer",
      title: "Specialist Services Under One Roof",
      subtitle: "From routine check-ups to complex procedures — our eight departments cover the full spectrum of care.",
    },
    doctors: {
      eyebrow: "Our Team",
      title: "Meet Our Specialist Physicians",
      subtitle: "Every doctor on our team is board-certified, fellowship-trained, and committed to evidence-based practice.",
    },
    process: {
      eyebrow: "How It Works",
      title: "Your Care Journey in Three Steps",
      backgroundImage: `${BASE}/bg/process_bg_1.jpg`,
      steps: [
        {
          number: "01",
          title: "Book Your Appointment",
          copy: "Schedule online, by phone, or walk in. Same-day slots are available for urgent consultations.",
          icon: `${BASE}/icons/service_icon_5.png`,
        },
        {
          number: "02",
          title: "Specialist Consultation",
          copy: "Meet your specialist. They review your history, order any necessary diagnostics, and explain your options clearly.",
          icon: `${BASE}/icons/service_icon_6.png`,
        },
        {
          number: "03",
          title: "Personalised Treatment",
          copy: "Receive a tailored treatment plan and follow-up support. We stay with you through every stage of your care.",
          icon: `${BASE}/icons/service_icon_7.png`,
        },
      ],
    },
    testimonials: {
      eyebrow: "Patient Stories",
      title: "What Our Patients Say",
      items: [
        {
          id: "t1",
          author: "Margaret T.",
          role: "Cardiology Patient",
          avatar: `${BASE}/testimonials/avatar_1.png`,
          body: "From my first appointment to post-surgery follow-up, the cardiology team was exceptional. Dr. Carter took the time to explain every step — I never felt like just a number.",
          rating: 5,
        },
        {
          id: "t2",
          author: "Daniel R.",
          role: "Orthopedics Patient",
          avatar: `${BASE}/testimonials/avatar_2.png`,
          body: "After my knee replacement with Dr. Evans, I was back on the golf course in eight weeks. The physiotherapy team and the follow-up care were outstanding.",
          rating: 5,
        },
        {
          id: "t3",
          author: "Fatima A.",
          role: "Pediatrics Parent",
          avatar: `${BASE}/testimonials/avatar_3.png`,
          body: "Dr. Chen has been our family's pediatrician for three years. She genuinely listens, explains everything clearly, and our kids actually look forward to their check-ups!",
          rating: 5,
        },
      ],
    },
    cta: {
      title: "Ready to Take the Next Step?",
      subtitle:
        "Book a consultation today. Our team will help you find the right specialist and the fastest path to feeling better.",
      image: `${BASE}/bg/cta_bg_1.jpeg`,
      cta: { label: "Book Appointment", href: "/templates/medical-center-1/preview/appointment/request" },
      ctaSecondary: { label: "Call Us Now", href: "tel:+18005550200" },
    },
    newsletter: {
      title: "Health Tips & Updates",
      subtitle: "Subscribe to receive expert health advice, preventive care reminders, and news from our specialists.",
      placeholder: "Enter your email address",
    },
  },

  legal: {
    privacy: "#",
    terms:   "#",
    cookies: "#",
  },
};
