/**
 * Shata Website Platform — shared data layer.
 * Drives:
 *   - parent page (/services/website-platform)
 *   - feature pages (/services/website-platform/features/[slug])
 *   - industry pages (/services/website-platform/industries/[slug])
 *
 * Add new features or industries here and the entire system updates.
 */

export type FeatureOutcome = { title: string; copy: string };
export type FeatureStep = { number: string; title: string; copy: string };
export type FeatureProof = { metric: string; label: string; copy: string };

export type WebsitePlatformFeature = {
  number: string;
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  heroLine: string;
  outcomes: FeatureOutcome[];
  steps: FeatureStep[];
  stackNodes: string[];
  proofPoints: FeatureProof[];
  ctaLabel: string;
};

export type IndustryTemplateSection = { title: string; copy: string };
export type IndustryFlowStep = { step: string; label: string; copy: string };
export type IndustryTrust = { title: string; copy: string };

export type WebsiteIndustry = {
  domain: string;
  slug: string;
  title: string;
  tag: string;
  description: string;
  heroLine: string;
  templateSections: IndustryTemplateSection[];
  includedFeatures: string[];
  conversionFlow: IndustryFlowStep[];
  trustSignals: IndustryTrust[];
  ctaLabel: string;
};

/* ------------------------------------------------------------------ */
/* Features                                                            */
/* ------------------------------------------------------------------ */

export const websitePlatformFeatures: WebsitePlatformFeature[] = [
  {
    number: "01",
    slug: "templates",
    title: "Website Templates",
    subtitle: "Premium template systems",
    description: "Start from premium template systems customized to your business.",
    heroLine: "Templates that already think like your business — not blank canvases pretending to be a builder.",
    outcomes: [
      { title: "Launch in days, not months", copy: "Skip the empty-canvas problem. Start from a structured template designed for your industry." },
      { title: "Premium first impression", copy: "Every template is shaped around modern conversion patterns — typography, hierarchy, contrast." },
      { title: "Customized, not cloned", copy: "Your branding, copy, services, images, and pages replace the placeholders before you ever see it." },
      { title: "Built to scale", copy: "Add pages, services, products, or sections later without rebuilding the foundation." },
    ],
    steps: [
      { number: "01", title: "Pick your template", copy: "Choose from clinic, ecommerce, law firm, repair, restaurant, agency, and more." },
      { number: "02", title: "Send business info", copy: "Send logo, services, copy, and any reference websites you like." },
      { number: "03", title: "We customize", copy: "Shata adapts the template to your branding, services, and content." },
      { number: "04", title: "We publish", copy: "Domain, SSL, hosting, and forms wired in and tested before launch." },
    ],
    stackNodes: ["Template", "Branding", "Content", "Pages", "Forms", "Live"],
    proofPoints: [
      { metric: "10+", label: "Industry systems", copy: "Templates engineered around real workflows — clinics, ecommerce, legal, auto, and more." },
      { metric: "100%", label: "Customized", copy: "No template ships with placeholder text. Every word, image, and section is yours." },
      { metric: "1 week", label: "Typical launch", copy: "From kickoff to live website in a single focused launch sprint." },
    ],
    ctaLabel: "Pick a template",
  },
  {
    number: "02",
    slug: "hosting-ssl",
    title: "Hosting & SSL",
    subtitle: "Secure managed hosting",
    description: "Your website stays secure, live, and managed without technical setup.",
    heroLine: "Enterprise-grade hosting and SSL — wired in, monitored, and never your problem.",
    outcomes: [
      { title: "Zero hosting decisions", copy: "No control panels, no server configs, no plan-comparison spreadsheets." },
      { title: "SSL on day one", copy: "Every site ships with HTTPS — auto-renewed, never expired, never broken." },
      { title: "Performance tuned", copy: "Caching, compression, and image optimization configured at the platform level." },
      { title: "Monitored uptime", copy: "Shata watches the infrastructure so a downed site doesn't quietly cost you leads." },
    ],
    steps: [
      { number: "01", title: "We provision", copy: "Hosting environment created, configured, and locked down for production." },
      { number: "02", title: "We secure", copy: "SSL certificate issued and bound — automatic renewal forever." },
      { number: "03", title: "We optimize", copy: "Caching layers, asset compression, and CDN routing tuned for your audience." },
      { number: "04", title: "We watch", copy: "Uptime, SSL expiry, and performance monitored continuously." },
    ],
    stackNodes: ["DNS", "SSL", "Hosting", "CDN", "Cache", "Monitor"],
    proofPoints: [
      { metric: "99.9%", label: "Target uptime", copy: "Built on infrastructure with redundancy and global edge delivery." },
      { metric: "0", label: "Hosting tickets", copy: "Clients never log into a hosting panel. We manage it end-to-end." },
      { metric: "Auto", label: "SSL renewal", copy: "Certificates renew on a schedule — your site stays trusted by browsers." },
    ],
    ctaLabel: "Move my hosting to Shata",
  },
  {
    number: "03",
    slug: "client-dashboard",
    title: "Client Dashboard",
    subtitle: "Edit without developers",
    description: "Simple editing for text, images, services, products, and leads.",
    heroLine: "A focused control panel — not a confusing CMS. Edit in seconds, publish with one click.",
    outcomes: [
      { title: "Edit anything in seconds", copy: "Update text, swap images, change hours, or add a service without touching code." },
      { title: "No CMS learning curve", copy: "Designed for non-technical owners — no plugins, no themes, no settings rabbit holes." },
      { title: "Lead inbox built in", copy: "Every form submission lands in the dashboard, ready to follow up." },
      { title: "Publish with confidence", copy: "Changes are previewed before going live. No broken pages." },
    ],
    steps: [
      { number: "01", title: "Log in", copy: "Secure login with your business email." },
      { number: "02", title: "Edit content", copy: "Click the section you want to change — text, image, service, product." },
      { number: "03", title: "Preview", copy: "See exactly what your customers will see before publishing." },
      { number: "04", title: "Publish", copy: "One button. Live in seconds. No deployments to wait for." },
    ],
    stackNodes: ["Editor", "Pages", "Services", "Products", "Leads", "Publish"],
    proofPoints: [
      { metric: "<60s", label: "Average edit", copy: "Most content edits are made and published in under a minute." },
      { metric: "0", label: "Plugins to manage", copy: "No theme conflicts, no security patches to chase." },
      { metric: "1-click", label: "Publishing", copy: "Edits go live instantly — no rebuild, no deploy, no waiting." },
    ],
    ctaLabel: "See the dashboard",
  },
  {
    number: "04",
    slug: "domain-options",
    title: "Domain Options",
    subtitle: "Subdomain or custom domain",
    description: "Use a Shata subdomain, connect your domain, or register a new one.",
    heroLine: "Three ways to go live — pick the one that fits your timeline and budget.",
    outcomes: [
      { title: "Launch in hours", copy: "Use a Shata subdomain like yourbrand.shatasolutions.com to publish immediately." },
      { title: "Bring your own domain", copy: "We handle DNS, SSL, and migration so your existing domain points to your new site." },
      { title: "Or we register a new one", copy: "Shata helps you find, secure, and connect a brand-new domain." },
      { title: "Move up anytime", copy: "Start on a subdomain, upgrade to a custom domain whenever you're ready." },
    ],
    steps: [
      { number: "01", title: "Choose your address", copy: "Subdomain, your existing domain, or a brand-new registration." },
      { number: "02", title: "We configure DNS", copy: "All A, CNAME, MX, and TXT records set up correctly." },
      { number: "03", title: "We bind SSL", copy: "Certificate issued for your exact domain." },
      { number: "04", title: "We publish", copy: "Site goes live and propagates globally." },
    ],
    stackNodes: ["Domain", "DNS", "SSL", "Hosting", "Email", "Live"],
    proofPoints: [
      { metric: "3", label: "Address options", copy: "Subdomain, connect existing, or register new — all priced clearly." },
      { metric: "Same-day", label: "Subdomain launch", copy: "A Shata subdomain can be live within hours of kickoff." },
      { metric: "Free", label: "Migration help", copy: "Bringing a domain from another provider is included in setup." },
    ],
    ctaLabel: "Pick my address",
  },
  {
    number: "05",
    slug: "business-email",
    title: "Business Email Add-on",
    subtitle: "Professional inbox setup",
    description: "Connect professional email like info@yourbrand.com.",
    heroLine: "Look like a serious business — not a Gmail account hiding behind a logo.",
    outcomes: [
      { title: "Email on your domain", copy: "info@, sales@, hello@ — choose any address that matches your brand." },
      { title: "Configured for deliverability", copy: "SPF, DKIM, and DMARC records set up so your emails reach the inbox, not spam." },
      { title: "Works with any client", copy: "Use it on phone, browser, Outlook, Apple Mail — wherever you already work." },
      { title: "One trusted identity", copy: "Customers see consistent branding from your website, forms, and email replies." },
    ],
    steps: [
      { number: "01", title: "Pick your addresses", copy: "Decide which inboxes you need — info, sales, support, or named users." },
      { number: "02", title: "We provision mailboxes", copy: "Mailboxes created and ready before you give the address out." },
      { number: "03", title: "We configure DNS", copy: "MX, SPF, DKIM, DMARC records set so deliverability is high from day one." },
      { number: "04", title: "We hand it off", copy: "You log in, change passwords, and start sending immediately." },
    ],
    stackNodes: ["Domain", "MX", "Mailbox", "SPF/DKIM", "Inbox", "Replies"],
    proofPoints: [
      { metric: "100%", label: "Deliverability setup", copy: "Every domain ships with SPF, DKIM, and DMARC properly configured." },
      { metric: "Any client", label: "Compatible", copy: "Outlook, Gmail, Apple Mail, mobile apps — all supported." },
      { metric: "Pro", label: "Brand identity", copy: "info@yourbrand.com signals seriousness in every message you send." },
    ],
    ctaLabel: "Set up my business email",
  },
  {
    number: "06",
    slug: "lead-forms",
    title: "Lead Forms",
    subtitle: "Capture and route leads",
    description: "Capture inquiries and route them to email or CRM.",
    heroLine: "Every form is a revenue line — captured, tracked, and routed to the right place.",
    outcomes: [
      { title: "Never lose an inquiry", copy: "Every submission is stored and emailed — no more lost messages." },
      { title: "Routed where you work", copy: "Send leads to email, WhatsApp, your CRM, or a Google Sheet." },
      { title: "Spam-resistant", copy: "Honeypot, rate limiting, and validation built in — clean leads only." },
      { title: "Mobile-first", copy: "Forms work flawlessly on phones — where most leads actually come from." },
    ],
    steps: [
      { number: "01", title: "Pick the form", copy: "Contact, booking, quote, callback, consultation — or a custom flow." },
      { number: "02", title: "Define the fields", copy: "Name, phone, service, date, notes — only what you need." },
      { number: "03", title: "Choose the routing", copy: "Email inbox, WhatsApp, CRM webhook, or all three." },
      { number: "04", title: "Test and launch", copy: "We send a test lead end-to-end before you go live." },
    ],
    stackNodes: ["Form", "Validate", "Submit", "Route", "Notify", "Follow up"],
    proofPoints: [
      { metric: "Multi-channel", label: "Routing", copy: "Email + WhatsApp + CRM at the same time, no plugins required." },
      { metric: "Built in", label: "Spam control", copy: "Honeypot and rate limiting block bots without annoying captchas." },
      { metric: "100%", label: "Mobile-ready", copy: "Forms render and submit reliably on every modern device." },
    ],
    ctaLabel: "Add lead forms",
  },
  {
    number: "07",
    slug: "booking-orders",
    title: "Booking / Orders",
    subtitle: "Booking and order flows",
    description: "Add booking, service requests, payment links, or order flows.",
    heroLine: "Turn the website into the front door of your operations — bookings, requests, and orders.",
    outcomes: [
      { title: "Bookings handled online", copy: "Customers pick a service, date, time, and submit — no phone tag." },
      { title: "Service requests structured", copy: "Quote forms collect exactly what your team needs to respond accurately." },
      { title: "Payment links built in", copy: "Charge a deposit, sell a package, or take an order with a single link." },
      { title: "One operations layer", copy: "Bookings, requests, and orders all land in one place to manage." },
    ],
    steps: [
      { number: "01", title: "Map the flow", copy: "We model your service, hours, and what info you need from customers." },
      { number: "02", title: "Build the form", copy: "Booking, request, or order form designed around your operations." },
      { number: "03", title: "Wire payments", copy: "Add Stripe-style payment links if you take deposits or sell online." },
      { number: "04", title: "Route and notify", copy: "New requests notify the right person and land in your inbox or CRM." },
    ],
    stackNodes: ["Pick", "Schedule", "Submit", "Pay", "Notify", "Fulfill"],
    proofPoints: [
      { metric: "24/7", label: "Customer self-serve", copy: "Bookings come in while your team sleeps — ready when they open." },
      { metric: "Stripe-ready", label: "Payments", copy: "Payment links integrate with the stack you already use to get paid." },
      { metric: "Inbox + CRM", label: "Routing", copy: "New requests are visible everywhere your team already looks." },
    ],
    ctaLabel: "Add bookings or orders",
  },
  {
    number: "08",
    slug: "analytics",
    title: "Analytics",
    subtitle: "Track performance",
    description: "Track visits, leads, and conversion signals from one panel.",
    heroLine: "See what's actually working — visits, leads, conversions, sources — not vanity metrics.",
    outcomes: [
      { title: "One dashboard", copy: "No GA4 maze. The numbers that matter, on one screen." },
      { title: "Lead-aware", copy: "Track form submissions, calls, and bookings — not just page views." },
      { title: "Source attribution", copy: "See which channels actually bring leads — search, social, ads, referrals." },
      { title: "Privacy-respecting", copy: "Tracking is configured to honor consent and modern privacy expectations." },
    ],
    steps: [
      { number: "01", title: "We instrument", copy: "Visit tracking, form events, and booking conversions wired up." },
      { number: "02", title: "We tag sources", copy: "Campaign URLs and referrer mapping configured for attribution." },
      { number: "03", title: "You log in", copy: "Open the analytics tab in the dashboard whenever you want a snapshot." },
      { number: "04", title: "We tune", copy: "We refine event tracking as your business evolves." },
    ],
    stackNodes: ["Visits", "Sources", "Forms", "Conversions", "Reports", "Decisions"],
    proofPoints: [
      { metric: "1 panel", label: "Unified view", copy: "Visits + leads + conversions on a single screen — no tab-switching." },
      { metric: "Source-aware", label: "Attribution", copy: "Know which channels are paying off, not just total traffic." },
      { metric: "Consent-ready", label: "Privacy", copy: "Built to respect consent banners and modern privacy laws." },
    ],
    ctaLabel: "Turn on analytics",
  },
  {
    number: "09",
    slug: "support-maintenance",
    title: "Support & Maintenance",
    subtitle: "Managed updates",
    description: "Keep the website updated without technical stress.",
    heroLine: "Your website never goes stale — content updates, fixes, and tuning handled by the team that built it.",
    outcomes: [
      { title: "No DIY updates", copy: "Need a new page, service, or section? Send a request — we ship it." },
      { title: "Always patched", copy: "Security, performance, and dependency updates handled at the platform level." },
      { title: "One channel", copy: "Email or WhatsApp — every request goes to the same place and gets resolved." },
      { title: "Predictable cost", copy: "Maintenance is included in the platform plan, not billed by the hour." },
    ],
    steps: [
      { number: "01", title: "You request", copy: "Send a change — text, image, page, form tweak — through the dashboard or email." },
      { number: "02", title: "We ship", copy: "Most requests are delivered within the same business day." },
      { number: "03", title: "We monitor", copy: "Uptime, SSL, and performance watched continuously in the background." },
      { number: "04", title: "We report", copy: "Monthly snapshot of what changed, what's healthy, what needs attention." },
    ],
    stackNodes: ["Request", "Build", "Test", "Publish", "Monitor", "Report"],
    proofPoints: [
      { metric: "Same day", label: "Most updates", copy: "Small content changes typically ship the same business day." },
      { metric: "Included", label: "In the plan", copy: "Maintenance is part of the platform — no surprise hourly invoices." },
      { metric: "Monthly", label: "Health report", copy: "You stay informed without having to chase the agency." },
    ],
    ctaLabel: "Hand off maintenance",
  },
];

/* ------------------------------------------------------------------ */
/* Industries                                                          */
/* ------------------------------------------------------------------ */

const commonFeatures = [
  "Premium template",
  "Custom branding",
  "Responsive mobile design",
  "Hosting & SSL included",
  "Lead form & inbox",
  "WhatsApp button",
  "Analytics dashboard",
  "Managed updates",
];

export const websiteIndustries: WebsiteIndustry[] = [
  {
    domain: "clinics.com",
    slug: "clinics",
    title: "Clinics",
    tag: "Booking flow",
    description: "Appointments, services, contact forms, WhatsApp, and location built into every clinic template.",
    heroLine: "A clinic website that turns visitors into booked appointments — without the back-and-forth.",
    templateSections: [
      { title: "Specialties & services", copy: "Clear service pages so patients understand exactly what you treat." },
      { title: "Doctor & team profiles", copy: "Names, photos, credentials, and specialties to build immediate trust." },
      { title: "Appointment booking", copy: "Pick a service, date, and time — request lands in your inbox or CRM." },
      { title: "Insurance & policies", copy: "Insurance partners, payment options, and clinic policies clearly listed." },
      { title: "Location & hours", copy: "Map, address, parking notes, and weekly hours always up to date." },
      { title: "Patient inquiry forms", copy: "Pre-visit questions captured before the patient walks in." },
    ],
    includedFeatures: [...commonFeatures, "Doctor profile pages", "Insurance partners block", "Multi-branch ready"],
    conversionFlow: [
      { step: "01", label: "Visitor lands", copy: "Patient finds the clinic via search, ads, or referral." },
      { step: "02", label: "Reviews services", copy: "Reads about specialties, doctors, and what to expect." },
      { step: "03", label: "Books appointment", copy: "Submits booking request with service and preferred time." },
      { step: "04", label: "Lead routed", copy: "Request lands in your inbox and CRM — front desk responds." },
      { step: "05", label: "Patient confirmed", copy: "Appointment confirmed, reminder sent, patient shows up." },
    ],
    trustSignals: [
      { title: "Real doctor profiles", copy: "Patients trust faces and credentials, not generic avatars." },
      { title: "Patient testimonials", copy: "Quotes from real patients build social proof on every visit." },
      { title: "Clear policies", copy: "Transparent insurance, fees, and cancellation policies build confidence." },
    ],
    ctaLabel: "Start your clinic website",
  },
  {
    domain: "dmvautoservices.com",
    slug: "dmv-auto-services",
    title: "DMV / Auto Services",
    tag: "Service requests",
    description: "Document requests, service lists, and appointment forms — built for service-heavy operations.",
    heroLine: "An auto-services site that handles document requests and appointments without phone overload.",
    templateSections: [
      { title: "Service catalog", copy: "Registration, title transfer, plates, inspections — every service explained." },
      { title: "Document checklist", copy: "What customers need to bring, by service type, before they show up." },
      { title: "Appointment requests", copy: "Date, time, and service type captured online to reduce walk-in load." },
      { title: "FAQ & policies", copy: "Common questions answered to deflect repetitive phone calls." },
      { title: "Branch locator", copy: "Multi-branch businesses get location, hours, and directions per office." },
    ],
    includedFeatures: [...commonFeatures, "Document checklists", "Branch locator", "Service price sheet"],
    conversionFlow: [
      { step: "01", label: "Visitor arrives", copy: "Customer needs a registration, title, or document service." },
      { step: "02", label: "Finds service", copy: "Reads what's required and how long it takes." },
      { step: "03", label: "Books appointment", copy: "Picks date, time, and branch — submits the form." },
      { step: "04", label: "Lead routed", copy: "Office gets the request and confirms availability." },
      { step: "05", label: "Customer served", copy: "Customer arrives prepared with the right documents." },
    ],
    trustSignals: [
      { title: "Clear pricing", copy: "Up-front pricing per service eliminates surprise-fee complaints." },
      { title: "Government compliance", copy: "Templates make compliance and disclosures easy to surface." },
      { title: "Multi-language ready", copy: "Bilingual content options for diverse customer bases." },
    ],
    ctaLabel: "Start your DMV/Auto site",
  },
  {
    domain: "lawfirms.com",
    slug: "law-firms",
    title: "Law Firms",
    tag: "Consultation forms",
    description: "Consultation forms, practice areas, and trust sections that read like a serious legal brand.",
    heroLine: "A law firm website that signals authority — and converts the right clients into consultations.",
    templateSections: [
      { title: "Practice areas", copy: "Each practice area gets its own page with results, scope, and process." },
      { title: "Attorney profiles", copy: "Bios, education, bar admissions, and credentials presented seriously." },
      { title: "Consultation request", copy: "Pre-screened consultation form to filter and qualify potential clients." },
      { title: "Case results & insights", copy: "Selected outcomes and articles that demonstrate expertise." },
      { title: "Office locations", copy: "Each office with map, phone, and contact for the right local market." },
    ],
    includedFeatures: [...commonFeatures, "Practice area pages", "Attorney bio system", "Consultation pre-screen"],
    conversionFlow: [
      { step: "01", label: "Lead arrives", copy: "Potential client searches for a practice area or attorney." },
      { step: "02", label: "Reviews credibility", copy: "Reads attorney bios, results, and articles." },
      { step: "03", label: "Submits consultation", copy: "Fills the qualifying form with case details." },
      { step: "04", label: "Lead routed", copy: "Intake team triages and assigns to the right attorney." },
      { step: "05", label: "Consultation booked", copy: "Qualified leads turn into scheduled consultations." },
    ],
    trustSignals: [
      { title: "Bar admissions", copy: "Visible credentials reassure serious clients." },
      { title: "Selected results", copy: "Anonymized outcomes demonstrate proven results." },
      { title: "Editorial voice", copy: "Articles and insights position the firm as a thought leader." },
    ],
    ctaLabel: "Start your law firm site",
  },
  {
    domain: "ecommerce.com",
    slug: "ecommerce",
    title: "Ecommerce",
    tag: "Order flows",
    description: "Products, categories, payment links, and order flows ready before your first customer arrives.",
    heroLine: "An ecommerce website ready to take orders on day one — categories, products, checkout, follow-up.",
    templateSections: [
      { title: "Product catalog", copy: "Categories and product pages built for browsing and conversion." },
      { title: "Product details", copy: "Photos, options, descriptions, and clear add-to-cart calls to action." },
      { title: "Checkout & payment", copy: "Payment links and order forms tuned for fast, low-friction checkout." },
      { title: "Promotions & offers", copy: "Bundle deals, banners, and promotional pages to drive AOV." },
      { title: "Order management", copy: "Orders captured in the dashboard, ready to fulfill or sync to a system." },
    ],
    includedFeatures: [...commonFeatures, "Category pages", "Payment link integration", "Order inbox"],
    conversionFlow: [
      { step: "01", label: "Visitor lands", copy: "Customer arrives via search, social, or campaign." },
      { step: "02", label: "Browses catalog", copy: "Explores categories and finds a product that fits." },
      { step: "03", label: "Adds to cart", copy: "Selects options and proceeds to checkout." },
      { step: "04", label: "Pays online", copy: "Completes payment via integrated payment links." },
      { step: "05", label: "Order fulfilled", copy: "Order routed to fulfillment, customer notified, repeat visit prompted." },
    ],
    trustSignals: [
      { title: "Secure checkout", copy: "SSL and trusted payment providers reassure first-time buyers." },
      { title: "Real product photos", copy: "High-quality product imagery converts better than stock." },
      { title: "Returns policy", copy: "Clear policies remove the last barrier to first purchase." },
    ],
    ctaLabel: "Start your ecommerce site",
  },
  {
    domain: "repaircenters.com",
    slug: "repair-centers",
    title: "Repair Centers",
    tag: "Quote tracking",
    description: "Service requests, quote forms, and tracking flows organized for fast operational teams.",
    heroLine: "A repair center website that captures jobs, quotes, and tracking — without operational chaos.",
    templateSections: [
      { title: "Service catalog", copy: "Categories of repairs, turnaround times, and pricing guidance." },
      { title: "Quote request", copy: "Customers describe the issue, attach photos, and request a quote." },
      { title: "Job tracking", copy: "Status updates customers can check without calling the shop." },
      { title: "Pickup & dropoff", copy: "Scheduling info, locations, and instructions for customers." },
      { title: "Warranty & guarantees", copy: "Clear warranty terms build trust and reduce disputes." },
    ],
    includedFeatures: [...commonFeatures, "Quote form with attachments", "Job status block", "Service area map"],
    conversionFlow: [
      { step: "01", label: "Customer arrives", copy: "Searches for repair help with a specific issue." },
      { step: "02", label: "Reviews services", copy: "Reads what you fix and typical turnaround." },
      { step: "03", label: "Requests quote", copy: "Submits issue description, photos, and contact info." },
      { step: "04", label: "Job confirmed", copy: "Team responds with quote and pickup/dropoff plan." },
      { step: "05", label: "Repair complete", copy: "Customer notified, picks up, and leaves a review." },
    ],
    trustSignals: [
      { title: "Warranty cover", copy: "Clear warranty signals professional, accountable work." },
      { title: "Real reviews", copy: "Customer testimonials prove turnaround and quality." },
      { title: "Service guarantee", copy: "Money-back or re-do guarantees lower decision risk." },
    ],
    ctaLabel: "Start your repair site",
  },
  {
    domain: "agencies.com",
    slug: "agencies",
    title: "Agencies",
    tag: "Lead capture",
    description: "Service packages, lead forms, and portfolio sections shaped for premium agency positioning.",
    heroLine: "An agency website that signals craft, credibility, and conversion — not a generic portfolio.",
    templateSections: [
      { title: "Service packages", copy: "Productized service tiers that prospects can scan and shortlist quickly." },
      { title: "Portfolio & case studies", copy: "Selected work with outcomes, not just screenshots." },
      { title: "Process & timeline", copy: "How you work — discovery, sprints, delivery — set client expectations." },
      { title: "Discovery call form", copy: "Qualified intake form that filters serious leads before the meeting." },
      { title: "Team & credentials", copy: "Founders, leads, and credibility markers presented like a serious firm." },
    ],
    includedFeatures: [...commonFeatures, "Case study layout", "Service package cards", "Discovery call form"],
    conversionFlow: [
      { step: "01", label: "Lead lands", copy: "Decision-maker arrives via search, referral, or content." },
      { step: "02", label: "Reads case studies", copy: "Evaluates relevance to their problem space." },
      { step: "03", label: "Submits intake", copy: "Fills discovery form with budget, scope, and timeline." },
      { step: "04", label: "Lead qualified", copy: "Sales lead reviews and books or politely declines." },
      { step: "05", label: "Discovery booked", copy: "Qualified meeting on the calendar — pipeline grows." },
    ],
    trustSignals: [
      { title: "Named clients", copy: "Logos and named clients prove the agency operates at scale." },
      { title: "Founder credibility", copy: "Founder bios and writing position the firm as expert-led." },
      { title: "Case outcomes", copy: "Real results, not just screenshots, justify premium pricing." },
    ],
    ctaLabel: "Start your agency site",
  },
  {
    domain: "carshowrooms.com",
    slug: "car-showrooms",
    title: "Car Showrooms",
    tag: "Inventory showcase",
    description: "Vehicle listings, financing inquiries, test drive forms, WhatsApp leads, and showroom location built into one clean website.",
    heroLine: "A showroom website that moves cars — inventory, test drives, financing, and walk-ins.",
    templateSections: [
      { title: "Inventory listings", copy: "Vehicle cards with photos, specs, price, and availability." },
      { title: "Vehicle detail pages", copy: "Galleries, specs, features, and finance calculators per vehicle." },
      { title: "Test drive booking", copy: "Form to schedule a test drive with date, time, and vehicle preference." },
      { title: "Financing inquiry", copy: "Lead form for finance applications routed to the finance team." },
      { title: "Showroom location", copy: "Map, hours, contact, and directions to the showroom." },
    ],
    includedFeatures: [...commonFeatures, "Inventory grid", "Test drive form", "Finance inquiry form"],
    conversionFlow: [
      { step: "01", label: "Buyer arrives", copy: "Browses listings or arrives via a specific vehicle search." },
      { step: "02", label: "Compares vehicles", copy: "Reads specs, photos, and pricing." },
      { step: "03", label: "Books test drive", copy: "Submits test drive form or finance inquiry." },
      { step: "04", label: "Lead routed", copy: "Sales rep contacts buyer to confirm test drive." },
      { step: "05", label: "Sale closed", copy: "Buyer visits, test drives, and closes the deal." },
    ],
    trustSignals: [
      { title: "Real inventory photos", copy: "Actual vehicle photos build trust over stock images." },
      { title: "Transparent pricing", copy: "Clear pricing reduces friction and bounces." },
      { title: "Showroom credibility", copy: "Staff, location, and reviews signal an established dealer." },
    ],
    ctaLabel: "Start your showroom site",
  },
  {
    domain: "barbershops.com",
    slug: "barber-shops",
    title: "Barber Shops",
    tag: "Appointment booking",
    description: "Service menus, barber profiles, booking requests, opening hours, gallery, and location-ready pages.",
    heroLine: "A barber shop website that fills the chair — bookings, menus, and walk-in conversions.",
    templateSections: [
      { title: "Service menu", copy: "Clear pricing for cuts, shaves, beards, and packages." },
      { title: "Barber profiles", copy: "Each barber with photo, specialty, and a personal touch." },
      { title: "Booking form", copy: "Customers pick a barber, service, and time slot." },
      { title: "Gallery", copy: "Recent cuts and styles to showcase craft." },
      { title: "Hours & location", copy: "Walk-in friendly with hours, address, and directions." },
    ],
    includedFeatures: [...commonFeatures, "Barber profile cards", "Service price menu", "Style gallery"],
    conversionFlow: [
      { step: "01", label: "Customer searches", copy: "Looks for a local barber or specific style." },
      { step: "02", label: "Reviews barbers", copy: "Picks a barber whose work matches the look." },
      { step: "03", label: "Books slot", copy: "Selects service, barber, and time." },
      { step: "04", label: "Booking confirmed", copy: "Shop confirms and reminds via WhatsApp." },
      { step: "05", label: "Customer served", copy: "Walks in, gets the cut, books a return visit." },
    ],
    trustSignals: [
      { title: "Barber portfolios", copy: "Visible craft converts hesitant first-timers." },
      { title: "Customer reviews", copy: "Local reviews matter most for repeat services." },
      { title: "Walk-in friendly", copy: "Hours and easy directions reduce friction." },
    ],
    ctaLabel: "Start your barber shop site",
  },
  {
    domain: "supermarkets.com",
    slug: "supermarkets",
    title: "Supermarkets",
    tag: "Product catalog",
    description: "Categories, offers, delivery areas, WhatsApp orders, branch locations, and weekly promotions.",
    heroLine: "A supermarket website that drives orders and walk-ins — promotions, delivery, and branches.",
    templateSections: [
      { title: "Category pages", copy: "Fresh, dairy, household, beverages — clear navigation." },
      { title: "Weekly promotions", copy: "Dynamic offers section refreshed with the week's deals." },
      { title: "Delivery requests", copy: "Order via WhatsApp or form — delivery zones clearly defined." },
      { title: "Branch locator", copy: "All branches with hours, address, and contact." },
      { title: "Loyalty & offers", copy: "Member offers and seasonal campaigns presented prominently." },
    ],
    includedFeatures: [...commonFeatures, "Promotions block", "Branch locator", "WhatsApp order"],
    conversionFlow: [
      { step: "01", label: "Customer browses", copy: "Searches for offers, products, or nearest branch." },
      { step: "02", label: "Sees promo", copy: "Spots weekly offer that matches their list." },
      { step: "03", label: "Places order", copy: "Submits WhatsApp order or visits branch." },
      { step: "04", label: "Lead routed", copy: "Order received and prepared by branch team." },
      { step: "05", label: "Customer served", copy: "Delivery or pickup completed and customer returns." },
    ],
    trustSignals: [
      { title: "Live promotions", copy: "Dynamic weekly offers prove activity and freshness." },
      { title: "Branch transparency", copy: "All locations and hours visible for trust." },
      { title: "Easy WhatsApp orders", copy: "Familiar ordering method removes friction." },
    ],
    ctaLabel: "Start your supermarket site",
  },
  {
    domain: "restaurantscafes.com",
    slug: "restaurants-cafes",
    title: "Restaurants & Cafes",
    tag: "Menu and orders",
    description: "Digital menus, reservations, delivery links, offers, gallery, branches, and customer inquiry flows.",
    heroLine: "A restaurant website that fills tables and drives orders — menu, reservations, and delivery.",
    templateSections: [
      { title: "Digital menu", copy: "Categories, items, prices, and dietary tags — always current." },
      { title: "Reservations", copy: "Table booking form with party size, date, and time." },
      { title: "Delivery links", copy: "Direct links to delivery partners for fast takeout." },
      { title: "Gallery", copy: "Food and ambience photos that drive visit decisions." },
      { title: "Branches", copy: "Locations, hours, and contact per outlet." },
    ],
    includedFeatures: [...commonFeatures, "Reservation form", "Menu manager", "Delivery integration"],
    conversionFlow: [
      { step: "01", label: "Diner arrives", copy: "Searches for cuisine, location, or menu." },
      { step: "02", label: "Reviews menu", copy: "Decides between dine-in, takeout, or delivery." },
      { step: "03", label: "Books table", copy: "Submits reservation or clicks delivery link." },
      { step: "04", label: "Lead routed", copy: "Restaurant confirms reservation or accepts order." },
      { step: "05", label: "Diner served", copy: "Visit completed, review prompted, return drive built." },
    ],
    trustSignals: [
      { title: "Real food photos", copy: "Quality imagery converts better than stock." },
      { title: "Reservation reliability", copy: "Confirmed reservations build repeat visits." },
      { title: "Multi-branch consistency", copy: "Menu and brand consistency across outlets." },
    ],
    ctaLabel: "Start your restaurant site",
  },
  {
    domain: "realestate.com",
    slug: "real-estate",
    title: "Real Estate",
    tag: "Property leads",
    description: "Property listings, inquiry forms, location sections, agent profiles, WhatsApp leads, and featured projects.",
    heroLine: "A real estate website that captures qualified buyer and tenant leads — properties, inquiries, agents.",
    templateSections: [
      { title: "Property listings", copy: "Cards with photos, price, beds, baths, and location." },
      { title: "Property detail pages", copy: "Galleries, floor plans, features, and inquiry forms per listing." },
      { title: "Inquiry forms", copy: "Buyer and tenant inquiries captured per property." },
      { title: "Agent profiles", copy: "Each agent with bio, contact, and listings handled." },
      { title: "Featured projects", copy: "New developments and exclusive listings highlighted." },
    ],
    includedFeatures: [...commonFeatures, "Listing grid", "Agent directory", "Property inquiry form"],
    conversionFlow: [
      { step: "01", label: "Buyer arrives", copy: "Searches for property by area, price, or type." },
      { step: "02", label: "Reviews listing", copy: "Reads details, sees photos, considers location." },
      { step: "03", label: "Submits inquiry", copy: "Requests viewing or more information." },
      { step: "04", label: "Lead routed", copy: "Agent contacted; viewing scheduled." },
      { step: "05", label: "Deal progressed", copy: "Buyer or tenant moves into negotiation." },
    ],
    trustSignals: [
      { title: "Verified listings", copy: "Active inventory signals a real, working brokerage." },
      { title: "Agent credibility", copy: "Named agents with track records build buyer trust." },
      { title: "Featured developments", copy: "Exclusive projects signal market access." },
    ],
    ctaLabel: "Start your real estate site",
  },
  {
    domain: "gymsfitness.com",
    slug: "gyms-fitness",
    title: "Gyms & Fitness",
    tag: "Membership leads",
    description: "Membership plans, trainer profiles, class schedules, transformation galleries, and lead forms.",
    heroLine: "A gym website that turns curiosity into trial visits and signed memberships.",
    templateSections: [
      { title: "Membership plans", copy: "Tiered plans with clear benefits, pricing, and call to join." },
      { title: "Trainer profiles", copy: "Coaches with specialty, credentials, and personal style." },
      { title: "Class schedule", copy: "Weekly schedule of classes with bookable spots." },
      { title: "Transformation gallery", copy: "Before/after results with member stories." },
      { title: "Trial pass form", copy: "Lead form for free trial visits or guest passes." },
    ],
    includedFeatures: [...commonFeatures, "Membership pricing cards", "Trainer profile cards", "Class schedule grid"],
    conversionFlow: [
      { step: "01", label: "Visitor arrives", copy: "Researches gyms in the area or for a specific goal." },
      { step: "02", label: "Reviews offer", copy: "Compares plans, classes, and trainers." },
      { step: "03", label: "Books trial", copy: "Submits free trial or guest pass form." },
      { step: "04", label: "Lead routed", copy: "Front desk follows up to schedule the visit." },
      { step: "05", label: "Member joins", copy: "Trial converts into a paid membership." },
    ],
    trustSignals: [
      { title: "Real transformations", copy: "Authentic member stories convert better than stock photos." },
      { title: "Certified trainers", copy: "Credentials reduce decision risk for serious athletes." },
      { title: "Active class calendar", copy: "Visible schedule proves the gym is alive and full." },
    ],
    ctaLabel: "Start your gym site",
  },
  {
    domain: "beautysalons.com",
    slug: "beauty-salons",
    title: "Beauty Salons",
    tag: "Service booking",
    description: "Service menus, booking requests, packages, gallery, staff profiles, and location-ready contact flows.",
    heroLine: "A beauty salon website that books appointments and keeps the chair busy all week.",
    templateSections: [
      { title: "Service menu", copy: "Hair, skin, nails, packages — with prices and durations." },
      { title: "Staff profiles", copy: "Stylists with specialty, photos, and bookable calendar." },
      { title: "Booking form", copy: "Pick service, stylist, and time — confirmed by the salon." },
      { title: "Gallery", copy: "Recent work that showcases craft and current trends." },
      { title: "Packages & offers", copy: "Bundle services and seasonal offers presented prominently." },
    ],
    includedFeatures: [...commonFeatures, "Stylist profiles", "Service menu", "Package cards"],
    conversionFlow: [
      { step: "01", label: "Customer searches", copy: "Looks for a salon for a specific service or stylist." },
      { step: "02", label: "Reviews work", copy: "Browses gallery and stylist portfolios." },
      { step: "03", label: "Books service", copy: "Submits booking with service, stylist, and time." },
      { step: "04", label: "Booking confirmed", copy: "Salon confirms and sends reminder." },
      { step: "05", label: "Customer served", copy: "Visit completed and rebook prompted." },
    ],
    trustSignals: [
      { title: "Stylist portfolios", copy: "Visible craft drives trust and bookings." },
      { title: "Local reviews", copy: "Local reviews are the strongest signal in beauty." },
      { title: "Hygiene & standards", copy: "Communicated standards reassure first visits." },
    ],
    ctaLabel: "Start your salon site",
  },
  {
    domain: "accountingfirms.com",
    slug: "accounting-firms",
    title: "Accounting Firms",
    tag: "Consultation requests",
    description: "Service pages, consultation forms, compliance sections, trust signals, and business inquiry flows.",
    heroLine: "An accounting firm website that signals expertise and converts business owners into clients.",
    templateSections: [
      { title: "Service pages", copy: "Bookkeeping, audit, tax, advisory — each with scope and fit." },
      { title: "Consultation form", copy: "Pre-screened consultation request that captures business size." },
      { title: "Compliance & credentials", copy: "Licensing, certifications, and standards presented clearly." },
      { title: "Industry expertise", copy: "Industries you specialize in — clinics, retail, ecommerce, etc." },
      { title: "Insights & articles", copy: "Recent updates on tax, regulation, and finance." },
    ],
    includedFeatures: [...commonFeatures, "Service pages", "Consultation form", "Credentials block"],
    conversionFlow: [
      { step: "01", label: "Business owner arrives", copy: "Searches for accounting help with a specific need." },
      { step: "02", label: "Reviews fit", copy: "Reads service pages and industry expertise." },
      { step: "03", label: "Books consultation", copy: "Submits inquiry with business size and need." },
      { step: "04", label: "Lead qualified", copy: "Partner reviews and schedules consultation." },
      { step: "05", label: "Engagement signed", copy: "Discovery call leads to engagement contract." },
    ],
    trustSignals: [
      { title: "Licensed credentials", copy: "Clear licensing reassures regulated clients." },
      { title: "Named partners", copy: "Partner bios position the firm as expert-led." },
      { title: "Industry expertise", copy: "Specialty signals a partner who already knows the business." },
    ],
    ctaLabel: "Start your accounting site",
  },
  {
    domain: "travelagencies.com",
    slug: "travel-agencies",
    title: "Travel Agencies",
    tag: "Trip inquiries",
    description: "Packages, destinations, visa help, hotel offers, inquiry forms, and WhatsApp-ready travel flows.",
    heroLine: "A travel agency website that turns scrolling into booked trips and visa appointments.",
    templateSections: [
      { title: "Packages & destinations", copy: "Curated trips with photos, itinerary, and price." },
      { title: "Visa services", copy: "Visa types, requirements, processing time, and application form." },
      { title: "Hotel offers", copy: "Featured hotel deals with quick booking inquiry." },
      { title: "Trip inquiry form", copy: "Custom trip request — destination, dates, party size." },
      { title: "WhatsApp-ready", copy: "WhatsApp button for fast travel consultation." },
    ],
    includedFeatures: [...commonFeatures, "Package cards", "Visa application form", "Trip inquiry form"],
    conversionFlow: [
      { step: "01", label: "Traveler arrives", copy: "Searches for destinations or trip ideas." },
      { step: "02", label: "Reviews packages", copy: "Compares trips, prices, and inclusions." },
      { step: "03", label: "Submits inquiry", copy: "Requests custom trip or visa assistance." },
      { step: "04", label: "Lead routed", copy: "Travel consultant follows up with options." },
      { step: "05", label: "Trip booked", copy: "Customer confirms, pays, and travels." },
    ],
    trustSignals: [
      { title: "Real itineraries", copy: "Detailed itineraries beat generic destination pages." },
      { title: "Visa expertise", copy: "Visible visa knowledge converts complex inquiries." },
      { title: "Reviews & testimonials", copy: "Past traveler reviews convert hesitant buyers." },
    ],
    ctaLabel: "Start your travel agency site",
  },
  {
    domain: "cleaningservices.com",
    slug: "cleaning-services",
    title: "Cleaning Services",
    tag: "Quote requests",
    description: "Service areas, quote forms, package cards, before-and-after galleries, and recurring booking flows.",
    heroLine: "A cleaning service website that captures quote requests and turns them into recurring revenue.",
    templateSections: [
      { title: "Service catalog", copy: "Residential, commercial, deep-clean, move-out — clearly listed." },
      { title: "Quote form", copy: "Property size, frequency, and details captured for accurate quotes." },
      { title: "Service area map", copy: "Where you operate, so leads filter themselves before submitting." },
      { title: "Before/after gallery", copy: "Visual proof of work quality." },
      { title: "Recurring booking", copy: "Weekly, biweekly, monthly recurring options." },
    ],
    includedFeatures: [...commonFeatures, "Quote form", "Service area block", "Before/after layout"],
    conversionFlow: [
      { step: "01", label: "Customer searches", copy: "Looks for a cleaner for home or office." },
      { step: "02", label: "Reviews services", copy: "Compares packages and reads reviews." },
      { step: "03", label: "Requests quote", copy: "Submits property details and preferred schedule." },
      { step: "04", label: "Quote sent", copy: "Team responds with accurate price and slot." },
      { step: "05", label: "Job recurring", copy: "First job converts into recurring schedule." },
    ],
    trustSignals: [
      { title: "Insurance & vetting", copy: "Insured staff and background checks build trust." },
      { title: "Real reviews", copy: "Local reviews convert hesitant homeowners." },
      { title: "Recurring guarantee", copy: "Easy cancellation removes recurring-booking friction." },
    ],
    ctaLabel: "Start your cleaning site",
  },
  {
    domain: "dentalclinics.com",
    slug: "dental-clinics",
    title: "Dental Clinics",
    tag: "Patient booking",
    description: "Treatment pages, appointment forms, doctor profiles, insurance notes, and location-ready patient flows.",
    heroLine: "A dental clinic website that books patients and reduces no-shows.",
    templateSections: [
      { title: "Treatments", copy: "Cleanings, orthodontics, cosmetic — each with cost guidance." },
      { title: "Doctor profiles", copy: "Each dentist with credentials, specialty, and bio." },
      { title: "Appointment form", copy: "Booking with treatment type, urgency, and preferred time." },
      { title: "Insurance partners", copy: "Accepted insurance providers listed clearly." },
      { title: "New patient packet", copy: "Forms and prep info patients can fill before arrival." },
    ],
    includedFeatures: [...commonFeatures, "Treatment pages", "Doctor profiles", "New patient form"],
    conversionFlow: [
      { step: "01", label: "Patient arrives", copy: "Searches for a dentist near them or for a treatment." },
      { step: "02", label: "Reviews trust", copy: "Reads doctor bios and treatment pages." },
      { step: "03", label: "Books appointment", copy: "Submits booking with treatment and timing." },
      { step: "04", label: "Reminded", copy: "Appointment confirmed and reminder sent to reduce no-shows." },
      { step: "05", label: "Patient seen", copy: "Visit completed, follow-up plan agreed." },
    ],
    trustSignals: [
      { title: "Doctor credentials", copy: "Visible credentials reassure new patients." },
      { title: "Insurance coverage", copy: "Listed insurance partners increase booking rate." },
      { title: "Patient reviews", copy: "Authentic reviews drive local conversion." },
    ],
    ctaLabel: "Start your dental clinic site",
  },
  {
    domain: "medicalcenters.com",
    slug: "medical-centers",
    title: "Medical Centers",
    tag: "Multi-specialty flow",
    description: "Departments, doctors, appointment forms, insurance information, and patient communication sections.",
    heroLine: "A multi-specialty medical center website that books patients across departments cleanly.",
    templateSections: [
      { title: "Departments", copy: "Each specialty as its own section with doctors and conditions." },
      { title: "Doctor directory", copy: "Searchable directory of physicians by specialty." },
      { title: "Appointment booking", copy: "Patients book by specialty, department, or doctor." },
      { title: "Insurance information", copy: "Accepted insurance and self-pay options listed." },
      { title: "Patient communication", copy: "Pre-visit instructions and post-visit follow-up." },
    ],
    includedFeatures: [...commonFeatures, "Department pages", "Doctor directory", "Multi-specialty booking"],
    conversionFlow: [
      { step: "01", label: "Patient arrives", copy: "Looks for a specialty or specific doctor." },
      { step: "02", label: "Finds department", copy: "Reads about the specialty and team." },
      { step: "03", label: "Books appointment", copy: "Submits booking by department or doctor." },
      { step: "04", label: "Triaged", copy: "Booking team confirms and prepares chart." },
      { step: "05", label: "Patient seen", copy: "Visit completed and follow-up scheduled." },
    ],
    trustSignals: [
      { title: "Multi-specialty depth", copy: "Comprehensive specialties signal a serious center." },
      { title: "Insurance breadth", copy: "Multiple insurance partners reach broader patient base." },
      { title: "Doctor credibility", copy: "Each physician with credentials and specialty." },
    ],
    ctaLabel: "Start your medical center site",
  },
  {
    domain: "pharmacies.com",
    slug: "pharmacies",
    title: "Pharmacies",
    tag: "Product and delivery",
    description: "Medicine categories, branch locations, delivery requests, WhatsApp orders, and offer sections.",
    heroLine: "A pharmacy website that drives delivery orders and walk-in traffic with confidence.",
    templateSections: [
      { title: "Medicine categories", copy: "Prescription, OTC, wellness, baby — with browsable pages." },
      { title: "Delivery request", copy: "Customers request delivery via form or WhatsApp." },
      { title: "Branch locator", copy: "Branches with hours, address, and contact." },
      { title: "Offers & loyalty", copy: "Promotions and loyalty offers presented prominently." },
      { title: "Pharmacist consultation", copy: "Form to ask a pharmacist before purchase." },
    ],
    includedFeatures: [...commonFeatures, "Branch locator", "Delivery request", "Pharmacist consultation"],
    conversionFlow: [
      { step: "01", label: "Customer arrives", copy: "Looks for a medication, branch, or offer." },
      { step: "02", label: "Browses or asks", copy: "Reads category or asks pharmacist." },
      { step: "03", label: "Requests delivery", copy: "Submits order via form or WhatsApp." },
      { step: "04", label: "Order routed", copy: "Branch prepares and dispatches." },
      { step: "05", label: "Customer served", copy: "Delivery completed; customer becomes recurring." },
    ],
    trustSignals: [
      { title: "Licensed branches", copy: "Visible licensing reassures regulated buyers." },
      { title: "Pharmacist access", copy: "Easy consultation builds repeat trust." },
      { title: "Delivery reliability", copy: "Quick, reliable delivery drives recurring orders." },
    ],
    ctaLabel: "Start your pharmacy site",
  },
  {
    domain: "petclinics.com",
    slug: "pet-clinics",
    title: "Pet Clinics",
    tag: "Appointment requests",
    description: "Pet services, doctor profiles, booking requests, vaccination reminders, and location sections.",
    heroLine: "A pet clinic website that books appointments and keeps owners coming back for vaccines and check-ups.",
    templateSections: [
      { title: "Services", copy: "Vaccinations, surgery, grooming, dental — each with detail." },
      { title: "Veterinarian profiles", copy: "Doctors with credentials and pet specialty." },
      { title: "Booking form", copy: "Pet name, species, service, and preferred time." },
      { title: "Vaccination reminders", copy: "Sign-up to get reminders for boosters and check-ups." },
      { title: "Location & emergency", copy: "Hours, address, emergency line, and after-hours info." },
    ],
    includedFeatures: [...commonFeatures, "Veterinarian profiles", "Vaccination reminder signup", "Pet booking form"],
    conversionFlow: [
      { step: "01", label: "Owner arrives", copy: "Searches for a vet or specific service." },
      { step: "02", label: "Reviews services", copy: "Reads doctor bios and services offered." },
      { step: "03", label: "Books appointment", copy: "Submits booking with pet info and need." },
      { step: "04", label: "Reminded", copy: "Confirmation and reminder sent." },
      { step: "05", label: "Pet seen", copy: "Visit completed; vaccination reminder set." },
    ],
    trustSignals: [
      { title: "Vet credentials", copy: "Visible credentials reassure protective owners." },
      { title: "Emergency access", copy: "Emergency line and hours build trust for serious cases." },
      { title: "Owner reviews", copy: "Local owner reviews convert new clients quickly." },
    ],
    ctaLabel: "Start your pet clinic site",
  },
  {
    domain: "hotelsguesthouses.com",
    slug: "hotels-guest-houses",
    title: "Hotels / Guest Houses",
    tag: "Booking inquiries",
    description: "Rooms, amenities, gallery, availability inquiry forms, location, and WhatsApp booking flow.",
    heroLine: "A hotel website that captures direct bookings and reduces dependency on third-party platforms.",
    templateSections: [
      { title: "Rooms & rates", copy: "Room categories with photos, capacity, and rate guidance." },
      { title: "Amenities", copy: "Pool, breakfast, Wi-Fi, parking — clearly listed." },
      { title: "Gallery", copy: "Hotel photos that drive booking decisions." },
      { title: "Availability inquiry", copy: "Date, party size, and room type captured for direct booking." },
      { title: "Location & directions", copy: "Map, transport, and nearby attractions." },
    ],
    includedFeatures: [...commonFeatures, "Room cards", "Availability inquiry", "Amenities block"],
    conversionFlow: [
      { step: "01", label: "Guest arrives", copy: "Searches for the hotel or compares to others." },
      { step: "02", label: "Reviews rooms", copy: "Compares photos, amenities, and rates." },
      { step: "03", label: "Submits inquiry", copy: "Requests availability for dates and room type." },
      { step: "04", label: "Booking confirmed", copy: "Hotel confirms and sends payment link." },
      { step: "05", label: "Guest hosted", copy: "Visit completed; review and rebook prompted." },
    ],
    trustSignals: [
      { title: "Real photos", copy: "Authentic photos beat third-party stock." },
      { title: "Direct booking benefit", copy: "Direct booking discounts reduce OTA dependence." },
      { title: "Reviews & ratings", copy: "Visible reviews from past guests build confidence." },
    ],
    ctaLabel: "Start your hotel site",
  },
  {
    domain: "educationcenters.com",
    slug: "education-centers",
    title: "Education Centers",
    tag: "Course leads",
    description: "Courses, schedules, instructor profiles, enrollment forms, and student inquiry workflows.",
    heroLine: "An education center website that turns course interest into enrollments and student leads.",
    templateSections: [
      { title: "Course catalog", copy: "Each course with outcomes, schedule, and price." },
      { title: "Instructor profiles", copy: "Teachers with credentials, experience, and style." },
      { title: "Schedule & cohorts", copy: "Upcoming intakes and course cohorts." },
      { title: "Enrollment form", copy: "Application with course, schedule, and student info." },
      { title: "Student inquiry", copy: "Form for general questions before enrollment." },
    ],
    includedFeatures: [...commonFeatures, "Course pages", "Instructor profiles", "Enrollment form"],
    conversionFlow: [
      { step: "01", label: "Student arrives", copy: "Searches for a course or skill." },
      { step: "02", label: "Reviews courses", copy: "Compares instructors, schedules, and outcomes." },
      { step: "03", label: "Submits enrollment", copy: "Applies for cohort with personal info." },
      { step: "04", label: "Lead routed", copy: "Admissions confirms enrollment or schedules call." },
      { step: "05", label: "Student starts", copy: "Onboarded into the course and cohort." },
    ],
    trustSignals: [
      { title: "Instructor credentials", copy: "Visible expertise drives serious enrollments." },
      { title: "Outcome stories", copy: "Past student outcomes prove program value." },
      { title: "Cohort transparency", copy: "Clear schedules build commitment." },
    ],
    ctaLabel: "Start your education center site",
  },
  {
    domain: "nurseriesdaycare.com",
    slug: "nurseries-daycare",
    title: "Nurseries / Daycare",
    tag: "Parent inquiries",
    description: "Programs, admissions, gallery, parent contact forms, location, and trust sections.",
    heroLine: "A nursery website that builds parent trust and books admissions tours.",
    templateSections: [
      { title: "Programs", copy: "Age groups, daily schedules, and learning approach." },
      { title: "Admissions", copy: "Process, requirements, and timeline for enrollment." },
      { title: "Gallery", copy: "Facility photos and activity scenes that build parent confidence." },
      { title: "Parent inquiry", copy: "Form to book a tour or ask admissions questions." },
      { title: "Trust & safety", copy: "Staff vetting, ratios, and safety standards." },
    ],
    includedFeatures: [...commonFeatures, "Program pages", "Admissions form", "Tour request form"],
    conversionFlow: [
      { step: "01", label: "Parent arrives", copy: "Searches for a nursery or daycare nearby." },
      { step: "02", label: "Reviews programs", copy: "Reads about ages, schedule, and approach." },
      { step: "03", label: "Books tour", copy: "Submits inquiry to visit and meet staff." },
      { step: "04", label: "Tour scheduled", copy: "Admissions team confirms tour." },
      { step: "05", label: "Child enrolled", copy: "Tour converts into enrollment." },
    ],
    trustSignals: [
      { title: "Safety standards", copy: "Visible safety practices reassure parents." },
      { title: "Staff vetting", copy: "Background checks and qualifications listed." },
      { title: "Parent reviews", copy: "Authentic reviews from current parents convert tours." },
    ],
    ctaLabel: "Start your nursery site",
  },
  {
    domain: "constructioncompanies.com",
    slug: "construction-companies",
    title: "Construction Companies",
    tag: "Project inquiries",
    description: "Services, project portfolio, quote forms, certifications, and contact flows for serious contractors.",
    heroLine: "A construction company website that wins contracts — services, projects, certifications, and quotes.",
    templateSections: [
      { title: "Services", copy: "Residential, commercial, fit-out, renovation — clearly scoped." },
      { title: "Project portfolio", copy: "Past projects with photos, scope, and outcomes." },
      { title: "Quote form", copy: "Project type, scope, and timeline captured for accurate quoting." },
      { title: "Certifications & licensing", copy: "Visible credentials reassure serious clients." },
      { title: "Team & equipment", copy: "Capabilities and key team members." },
    ],
    includedFeatures: [...commonFeatures, "Project portfolio grid", "Quote form", "Certifications block"],
    conversionFlow: [
      { step: "01", label: "Client arrives", copy: "Searches for a contractor for a specific project." },
      { step: "02", label: "Reviews portfolio", copy: "Evaluates past projects for fit and quality." },
      { step: "03", label: "Requests quote", copy: "Submits project details and timeline." },
      { step: "04", label: "Quote prepared", copy: "Team responds with proposal and meeting." },
      { step: "05", label: "Contract signed", copy: "Project kicked off after agreement." },
    ],
    trustSignals: [
      { title: "Licensed & insured", copy: "Visible licensing eliminates serious-buyer hesitation." },
      { title: "Real project photos", copy: "Authentic portfolios beat stock construction shots." },
      { title: "Client testimonials", copy: "Past client quotes anchor trust." },
    ],
    ctaLabel: "Start your construction site",
  },
  {
    domain: "homeservices.com",
    slug: "home-services",
    title: "Home Services",
    tag: "Job requests",
    description: "Service areas, quote forms, technician dispatch requests, package cards, and WhatsApp lead capture.",
    heroLine: "A home services website that captures service jobs and dispatches technicians efficiently.",
    templateSections: [
      { title: "Services", copy: "Plumbing, electrical, AC, handyman — clearly listed." },
      { title: "Service area", copy: "Cities and zones served, so leads filter themselves." },
      { title: "Quote form", copy: "Issue type, urgency, and address captured for dispatch." },
      { title: "Package cards", copy: "Maintenance packages and service contracts." },
      { title: "WhatsApp lead capture", copy: "Direct WhatsApp link for urgent jobs." },
    ],
    includedFeatures: [...commonFeatures, "Service area block", "Quote form", "Package pricing"],
    conversionFlow: [
      { step: "01", label: "Customer arrives", copy: "Searches for a technician or specific job." },
      { step: "02", label: "Reviews services", copy: "Picks the right service and reads pricing." },
      { step: "03", label: "Requests dispatch", copy: "Submits job with address and urgency." },
      { step: "04", label: "Technician dispatched", copy: "Team confirms slot and sends technician." },
      { step: "05", label: "Job completed", copy: "Job done; review and recurring offer prompted." },
    ],
    trustSignals: [
      { title: "Vetted technicians", copy: "Background checks and uniforms build confidence." },
      { title: "Transparent pricing", copy: "Up-front pricing reduces surprise-fee complaints." },
      { title: "Local reviews", copy: "Local reviews drive home-service decisions." },
    ],
    ctaLabel: "Start your home services site",
  },
  {
    domain: "eventplanners.com",
    slug: "event-planners",
    title: "Event Planners",
    tag: "Event inquiries",
    description: "Packages, galleries, inquiry forms, service areas, and consultation booking flows.",
    heroLine: "An event planner website that turns inspiration into booked weddings, corporate events, and parties.",
    templateSections: [
      { title: "Packages", copy: "Event types and tiered packages with clear inclusions." },
      { title: "Past events gallery", copy: "Real event photos that demonstrate style and craft." },
      { title: "Event inquiry form", copy: "Date, type, guest count, and budget captured for fit." },
      { title: "Consultation booking", copy: "Free planning call scheduled directly from the form." },
      { title: "Vendor partners", copy: "Trusted vendor network listed to signal scale." },
    ],
    includedFeatures: [...commonFeatures, "Event package cards", "Past events gallery", "Consultation form"],
    conversionFlow: [
      { step: "01", label: "Client arrives", copy: "Browses planners for an upcoming event." },
      { step: "02", label: "Reviews work", copy: "Compares past events and packages." },
      { step: "03", label: "Submits inquiry", copy: "Sends event details, date, and budget." },
      { step: "04", label: "Consultation scheduled", copy: "Planner confirms and books planning call." },
      { step: "05", label: "Event delivered", copy: "Event executed; testimonial and referral collected." },
    ],
    trustSignals: [
      { title: "Real event photos", copy: "Authentic galleries convert better than stock." },
      { title: "Vendor network", copy: "Visible partners signal experience and scale." },
      { title: "Client testimonials", copy: "Past clients drive trust for high-stakes events." },
    ],
    ctaLabel: "Start your event planner site",
  },
];
