import type { Pharmacy1Config } from "./types";

export const PHARMACY1_STORAGE_KEY = "shata-pharmacy-1-draft";

export const PHARMACY1_DEFAULTS: Pharmacy1Config = {
  brand: {
    name: "Shata Pharmacy",
    tagline: "Everyday pharmacy products, wellness goods, and helpful service.",
    email: "hello@shatapharmacy.com",
    phone: "(212) 555-0184",
    address: "Shata Pharmacy, New York",
  },
  theme: {
    primary: "#0a9a73",
    accent: "#ff5a3c",
    background: "#ffffff",
    text: "#071c1f",
  },
  header: {
    ctaLabel: "Shop Now",
    ctaHref: "/templates/pharmacy-1/preview/shop",
    nav: [
      { id: "home", label: "Home", href: "/templates/pharmacy-1/preview", enabled: true },
      { id: "about", label: "About", href: "/templates/pharmacy-1/preview/about", enabled: true },
      { id: "shop", label: "Shop", href: "/templates/pharmacy-1/preview/shop", enabled: true },
      { id: "categories", label: "Categories", href: "/templates/pharmacy-1/preview/categories", enabled: true },
      { id: "blog", label: "Blog", href: "/templates/pharmacy-1/preview/blog", enabled: true },
      { id: "contact", label: "Contact", href: "/templates/pharmacy-1/preview/contact", enabled: true },
    ],
  },
  homeSections: [
    { id: "hero", name: "Hero slider", type: "slider", content: "Discount banners from the pharmacy reference.", enabled: true },
    { id: "categories", name: "Product categories", type: "carousel", content: "Category icons and quick links.", enabled: true },
    { id: "featured", name: "Featured products", type: "products", content: "Featured pharmacy products.", enabled: true },
    { id: "offers", name: "Offers and banners", type: "banners", content: "Discount and promotion blocks.", enabled: true },
    { id: "blog", name: "News and blog", type: "blog", content: "Latest pharmacy articles.", enabled: true },
  ],
  heroBanners: [
    {
      id: "mask-offer",
      handle: "mask-offer",
      name: "Get 20% Discount Of N95 Mask",
      shortDescription: "Hero offer from the reference template.",
      description: "Promotional pharmacy banner using the original reference imagery.",
      image: "/templates/pharmacy1/img/slider/13.jpg",
      badge: "Offer",
      enabled: true,
      featured: true,
    },
  ],
  categories: [
    {
      id: "best-deals",
      handle: "best-deals",
      name: "Best Deals",
      shortDescription: "Popular pharmacy deals.",
      description: "Quick access to featured deals.",
      image: "/templates/pharmacy1/img/banner/1.jpg",
      enabled: true,
      featured: true,
    },
    {
      id: "accessories",
      handle: "accessories",
      name: "Accessories",
      shortDescription: "Everyday healthcare accessories.",
      description: "Supplies and accessories from the reference shop.",
      image: "/templates/pharmacy1/img/banner/2.jpg",
      enabled: true,
      featured: true,
    },
  ],
  products: [
    {
      id: "antiseptic-spray",
      handle: "antiseptic-spray",
      name: "Antiseptic Spray",
      shortDescription: "Reference product card.",
      description: "Product information is for template display only. Consult your healthcare professional before using healthcare products.",
      image: "/templates/pharmacy1/img/product/1.png",
      price: "$32.00",
      category: "best-deals",
      badge: "New",
      enabled: true,
      featured: true,
    },
    {
      id: "digital-stethoscope",
      handle: "digital-stethoscope",
      name: "Digital Stethoscope",
      shortDescription: "Reference product card.",
      description: "Product information is for template display only. Consult your healthcare professional before using healthcare products.",
      image: "/templates/pharmacy1/img/product/2.png",
      price: "$25.00",
      category: "accessories",
      enabled: true,
      featured: true,
    },
  ],
  offers: [
    {
      id: "free-shipping",
      handle: "free-shipping",
      name: "Free Shipping Over $100",
      shortDescription: "Offer banner from the reference checkout/cart content.",
      description: "Promotional messaging for ecommerce presentation.",
      image: "/templates/pharmacy1/img/banner/1.jpg",
      badge: "Deal",
      enabled: true,
      featured: true,
    },
  ],
  services: [
    {
      id: "wellness-support",
      handle: "wellness-support",
      name: "Wellness Product Support",
      shortDescription: "Helpful pharmacy product guidance.",
      description: "General product support only; consult your healthcare professional for medical advice.",
      image: "/templates/pharmacy1/img/service/1.jpg",
      enabled: true,
      featured: true,
    },
  ],
  brands: [
    {
      id: "brand-one",
      handle: "brand-one",
      name: "Wellness Brand",
      shortDescription: "Reference brand logo slot.",
      description: "Editable brand placement.",
      image: "/templates/pharmacy1/img/brand-logo/1.png",
      enabled: true,
      featured: true,
    },
  ],
  testimonials: [
    {
      id: "customer-care",
      handle: "customer-care",
      name: "Customer Care",
      shortDescription: "Friendly service and quick shopping flow.",
      description: "The template is easy to browse and makes pharmacy products simple to present.",
      image: "/templates/pharmacy1/img/testimonial/1.jpg",
      enabled: true,
      featured: true,
    },
  ],
  blog: [
    {
      id: "safe-product-shopping",
      handle: "safe-product-shopping",
      name: "How to Shop Pharmacy Products Safely",
      shortDescription: "Template blog article.",
      description: "General wellness content. Consult your healthcare professional for personal medical guidance.",
      image: "/templates/pharmacy1/img/blog/1.jpg",
      enabled: true,
      featured: true,
    },
  ],
  pages: [
    { id: "faq", title: "FAQ", slug: "faq", content: "Common questions for the Shata Pharmacy template.", enabled: true },
  ],
  contact: {
    heading: "Contact Shata Pharmacy",
    formTitle: "Send us a message",
    mapLabel: "Shata Pharmacy location",
    safetyNote: "Information on this template is not medical advice. Consult your healthcare professional.",
  },
  footer: {
    description: "A complete pharmacy ecommerce template adapted from the reference package.",
    copyright: "© 2026 Shata Pharmacy. All Rights Reserved.",
  },
};
