// lib/spaSalon1/defaults.ts
import type { SpaSalon1Config } from "./types";

export const defaultSpaSalon1Config: SpaSalon1Config = {
  brand: {
    name: "Shata Spa & Salon",
    tagline: "Luxury Spa & Beauty Experience",
    logo: "/templates/spaSalon1/images/logo.svg",
    logoWhite: "/templates/spaSalon1/images/logo-white.svg",
    email: "info@shatasolutions.com",
    phone: "+20 100 000 0000",
    address: "123 Luxury Lane",
    city: "Cairo",
    country: "Egypt",
    social: {
      facebook: "#",
      instagram: "#",
      twitter: "#",
      youtube: "#",
      pinterest: "#",
    },
  },
  theme: {
    activeTheme: "pink",
    primaryColor: "#f06292",
    accentColor: "#c9a07a",
  },
  navigation: {
    items: [
      {
        id: "nav-home",
        label: "Home",
        href: "/templates/spa-salon-1/preview",
      },
      {
        id: "nav-about",
        label: "About Us",
        href: "/templates/spa-salon-1/preview/about",
      },
      {
        id: "nav-services",
        label: "Services",
        href: "/templates/spa-salon-1/preview/services",
        children: [
          {
            id: "nav-services-list",
            label: "All Services",
            href: "/templates/spa-salon-1/preview/services",
          },
          {
            id: "nav-services-detail",
            label: "Service Details",
            href: "/templates/spa-salon-1/preview/services/facial-treatment",
          },
        ],
      },
      {
        id: "nav-gallery",
        label: "Gallery",
        href: "/templates/spa-salon-1/preview/gallery",
      },
      {
        id: "nav-team",
        label: "Our Team",
        href: "/templates/spa-salon-1/preview/team",
      },
      {
        id: "nav-pricing",
        label: "Pricing",
        href: "/templates/spa-salon-1/preview/pricing",
      },
      {
        id: "nav-blog",
        label: "Blog",
        href: "/templates/spa-salon-1/preview/blog",
      },
      {
        id: "nav-contact",
        label: "Contact",
        href: "/templates/spa-salon-1/preview/contact",
      },
    ],
    showBookingButton: true,
    bookingButtonText: "Book Appointment",
    bookingButtonHref: "/templates/spa-salon-1/preview/appointment",
    topbarEnabled: true,
    topbarPhone: "+20 100 000 0000",
    topbarEmail: "info@shatasolutions.com",
    topbarHours: "Mon–Sat: 9:00 AM – 8:00 PM",
  },
  heroSlides: [
    {
      id: "slide-1",
      image: "/templates/spaSalon1/images/slider/slide-1.jpg",
      subtitle: "Welcome to Shata Spa",
      title: "Relax. Rejuvenate. Revive.",
      description: "Indulge in our premium spa and beauty treatments designed to restore balance and beauty.",
      buttonText: "Book Appointment",
      buttonHref: "/templates/spa-salon-1/preview/appointment",
      secondaryButtonText: "Explore Services",
      secondaryButtonHref: "/templates/spa-salon-1/preview/services",
    },
    {
      id: "slide-2",
      image: "/templates/spaSalon1/images/slider/slide-2.jpg",
      subtitle: "Luxury Treatments",
      title: "The Art of Beauty",
      description: "Experience world-class beauty treatments by our expert therapists in a serene environment.",
      buttonText: "Our Services",
      buttonHref: "/templates/spa-salon-1/preview/services",
    },
    {
      id: "slide-3",
      image: "/templates/spaSalon1/images/slider/slide-3.jpg",
      subtitle: "Expert Team",
      title: "Beauty Is Our Passion",
      description: "Our certified specialists are dedicated to giving you the ultimate spa experience.",
      buttonText: "Meet the Team",
      buttonHref: "/templates/spa-salon-1/preview/team",
    },
  ],
  homeSections: [
    { id: "hero", type: "hero", enabled: true, order: 1, title: "Hero Slider" },
    { id: "about", type: "about", enabled: true, order: 2, title: "About Section" },
    { id: "services", type: "services", enabled: true, order: 3, title: "Services Section" },
    { id: "gallery", type: "gallery", enabled: true, order: 4, title: "Gallery Section" },
    { id: "team", type: "team", enabled: true, order: 5, title: "Team Section" },
    { id: "testimonials", type: "testimonials", enabled: true, order: 6, title: "Testimonials" },
    { id: "pricing", type: "pricing", enabled: true, order: 7, title: "Pricing Section" },
    { id: "blog", type: "blog", enabled: true, order: 8, title: "Blog Section" },
    { id: "cta", type: "cta", enabled: true, order: 9, title: "Call to Action" },
    { id: "instagram", type: "instagram", enabled: true, order: 10, title: "Instagram Feed" },
  ],
  services: [
    {
      id: "serv-1",
      handle: "facial-treatment",
      name: "Facial Treatment",
      category: "Skin Care",
      description: "Our deep cleansing facial removes impurities and revitalizes your skin for a radiant glow.",
      shortDescription: "Deep cleansing and revitalizing facial for radiant skin.",
      image: "/templates/spaSalon1/images/serv-01.png",
      duration: "60 min",
      price: 85,
      currency: "USD",
      featured: true,
      order: 1,
    },
    {
      id: "serv-2",
      handle: "body-massage",
      name: "Body Massage",
      category: "Body Treatments",
      description: "Full-body Swedish massage that relieves tension, improves circulation, and promotes deep relaxation.",
      shortDescription: "Full-body relaxation massage to relieve stress and tension.",
      image: "/templates/spaSalon1/images/serv-02.png",
      duration: "90 min",
      price: 110,
      currency: "USD",
      featured: true,
      order: 2,
    },
    {
      id: "serv-3",
      handle: "hair-styling",
      name: "Hair Styling",
      category: "Hair",
      description: "Expert hair styling services including cuts, blowouts, and special occasion styles.",
      shortDescription: "Professional hair styling for any occasion.",
      image: "/templates/spaSalon1/images/serv-03.png",
      duration: "45 min",
      price: 65,
      currency: "USD",
      featured: true,
      order: 3,
    },
    {
      id: "serv-4",
      handle: "manicure-pedicure",
      name: "Manicure & Pedicure",
      category: "Nail Care",
      description: "Luxury nail treatment including shaping, cuticle care, and polish for hands and feet.",
      shortDescription: "Complete luxury nail care for hands and feet.",
      image: "/templates/spaSalon1/images/serv-13.jpg",
      duration: "75 min",
      price: 75,
      currency: "USD",
      featured: false,
      order: 4,
    },
    {
      id: "serv-5",
      handle: "hot-stone-therapy",
      name: "Hot Stone Therapy",
      category: "Body Treatments",
      description: "Heated basalt stones melt away muscle tension and stress in this signature treatment.",
      shortDescription: "Therapeutic hot stone massage for deep muscle relaxation.",
      image: "/templates/spaSalon1/images/serv-14.jpg",
      duration: "90 min",
      price: 130,
      currency: "USD",
      featured: false,
      order: 5,
    },
    {
      id: "serv-6",
      handle: "aromatherapy",
      name: "Aromatherapy",
      category: "Wellness",
      description: "Essential oil-infused massage that balances body and mind through the power of scent.",
      shortDescription: "Balancing aromatherapy massage with essential oils.",
      image: "/templates/spaSalon1/images/serv-15.jpg",
      duration: "60 min",
      price: 95,
      currency: "USD",
      featured: false,
      order: 6,
    },
  ],
  pricingCategories: [
    {
      id: "cat-facial",
      name: "Facial Treatments",
      items: [
        { id: "p-f1", name: "Express Facial", price: 55, currency: "USD", duration: "30 min" },
        { id: "p-f2", name: "Deep Cleansing Facial", price: 85, currency: "USD", duration: "60 min" },
        { id: "p-f3", name: "Anti-Aging Facial", price: 110, currency: "USD", duration: "75 min" },
        { id: "p-f4", name: "Brightening Facial", price: 95, currency: "USD", duration: "60 min" },
      ],
    },
    {
      id: "cat-massage",
      name: "Massage Therapy",
      items: [
        { id: "p-m1", name: "Swedish Massage", price: 80, currency: "USD", duration: "60 min" },
        { id: "p-m2", name: "Deep Tissue Massage", price: 100, currency: "USD", duration: "60 min" },
        { id: "p-m3", name: "Hot Stone Massage", price: 130, currency: "USD", duration: "90 min" },
        { id: "p-m4", name: "Aromatherapy Massage", price: 95, currency: "USD", duration: "60 min" },
      ],
    },
    {
      id: "cat-hair",
      name: "Hair Services",
      items: [
        { id: "p-h1", name: "Haircut & Style", price: 65, currency: "USD", duration: "45 min" },
        { id: "p-h2", name: "Color & Highlights", price: 150, currency: "USD", duration: "120 min" },
        { id: "p-h3", name: "Blowout", price: 45, currency: "USD", duration: "30 min" },
        { id: "p-h4", name: "Keratin Treatment", price: 200, currency: "USD", duration: "180 min" },
      ],
    },
    {
      id: "cat-nails",
      name: "Nail Care",
      items: [
        { id: "p-n1", name: "Classic Manicure", price: 35, currency: "USD", duration: "30 min" },
        { id: "p-n2", name: "Gel Manicure", price: 55, currency: "USD", duration: "45 min" },
        { id: "p-n3", name: "Classic Pedicure", price: 45, currency: "USD", duration: "45 min" },
        { id: "p-n4", name: "Luxury Pedicure", price: 75, currency: "USD", duration: "60 min" },
      ],
    },
  ],
  team: [
    {
      id: "team-1",
      slug: "layla-hassan",
      name: "Layla Hassan",
      role: "Senior Spa Therapist",
      bio: "With over 10 years of experience, Layla specializes in holistic body treatments and facial therapies.",
      image: "/templates/spaSalon1/images/team-1.jpg",
      social: { instagram: "#", facebook: "#" },
      specialties: ["Hot Stone Therapy", "Deep Tissue Massage", "Facial Treatments"],
      order: 1,
    },
    {
      id: "team-2",
      slug: "sara-ali",
      name: "Sara Ali",
      role: "Master Hair Stylist",
      bio: "Sara brings creativity and precision to every hairstyle, trained in London and Cairo.",
      image: "/templates/spaSalon1/images/team-2.jpg",
      social: { instagram: "#", facebook: "#" },
      specialties: ["Hair Coloring", "Keratin Treatments", "Bridal Styling"],
      order: 2,
    },
    {
      id: "team-3",
      slug: "nour-ibrahim",
      name: "Nour Ibrahim",
      role: "Nail Artist",
      bio: "Nour is a certified nail technician specializing in intricate nail art and luxury manicures.",
      image: "/templates/spaSalon1/images/team-3.jpg",
      social: { instagram: "#", facebook: "#" },
      specialties: ["Nail Art", "Gel Extensions", "Luxury Pedicures"],
      order: 3,
    },
    {
      id: "team-4",
      slug: "hana-mostafa",
      name: "Hana Mostafa",
      role: "Aromatherapy Specialist",
      bio: "Hana is trained in clinical aromatherapy and blends custom essential oil treatments for each client.",
      image: "/templates/spaSalon1/images/team-4.jpg",
      social: { instagram: "#", facebook: "#" },
      specialties: ["Aromatherapy", "Swedish Massage", "Wellness Consultations"],
      order: 4,
    },
  ],
  gallery: [
    { id: "gal-1", src: "/templates/spaSalon1/images/gallery/img-1.jpg", alt: "Spa Treatment", category: "treatments", order: 1 },
    { id: "gal-2", src: "/templates/spaSalon1/images/gallery/img-2.jpg", alt: "Relaxation Room", category: "interior", order: 2 },
    { id: "gal-3", src: "/templates/spaSalon1/images/gallery/img-3.jpg", alt: "Facial Treatment", category: "treatments", order: 3 },
    { id: "gal-4", src: "/templates/spaSalon1/images/gallery/img-4.jpg", alt: "Hair Styling", category: "hair", order: 4 },
    { id: "gal-5", src: "/templates/spaSalon1/images/gallery/img-5.jpg", alt: "Massage Room", category: "interior", order: 5 },
    { id: "gal-6", src: "/templates/spaSalon1/images/gallery/img-6.jpg", alt: "Nail Art", category: "nails", order: 6 },
    { id: "gal-7", src: "/templates/spaSalon1/images/gallery/img-7.jpg", alt: "Body Treatment", category: "treatments", order: 7 },
    { id: "gal-8", src: "/templates/spaSalon1/images/gallery/img-8.jpg", alt: "Spa Reception", category: "interior", order: 8 },
    { id: "gal-9", src: "/templates/spaSalon1/images/gallery/img-9.jpg", alt: "Hot Stone Therapy", category: "treatments", order: 9 },
    { id: "gal-10", src: "/templates/spaSalon1/images/gallery/img-10.jpg", alt: "Beauty Room", category: "interior", order: 10 },
    { id: "gal-11", src: "/templates/spaSalon1/images/gallery/img-11.jpg", alt: "Manicure", category: "nails", order: 11 },
    { id: "gal-12", src: "/templates/spaSalon1/images/gallery/img-12.jpg", alt: "Hair Color", category: "hair", order: 12 },
  ],
  testimonials: [
    {
      id: "test-1",
      author: "Amira Khalil",
      role: "Regular Client",
      image: "/templates/spaSalon1/images/review-author-1.jpg",
      rating: 5,
      text: "Absolutely love this place. The facials are incredible and the staff makes you feel so welcome. I leave feeling completely refreshed every time.",
      service: "Facial Treatment",
      order: 1,
    },
    {
      id: "test-2",
      author: "Maya Sayed",
      role: "Loyal Customer",
      image: "/templates/spaSalon1/images/review-author-2.jpg",
      rating: 5,
      text: "The hot stone massage was beyond amazing. It's the best spa experience I've had in Cairo. Highly recommend to everyone!",
      service: "Hot Stone Therapy",
      order: 2,
    },
    {
      id: "test-3",
      author: "Dina Farouk",
      role: "Beauty Enthusiast",
      image: "/templates/spaSalon1/images/review-author-3.jpg",
      rating: 5,
      text: "Sara is the best hair stylist I've ever had. She understood exactly what I wanted and delivered perfection. Won't go anywhere else.",
      service: "Hair Styling",
      order: 3,
    },
  ],
  blog: [
    {
      id: "blog-1",
      slug: "top-5-benefits-of-spa-treatments",
      title: "Top 5 Benefits of Regular Spa Treatments",
      excerpt: "Discover how regular spa visits can improve your overall health, reduce stress, and enhance your natural beauty.",
      content: "<p>Regular spa treatments offer far more than just relaxation...</p>",
      image: "/templates/spaSalon1/images/blog/img-01.jpg",
      author: "Layla Hassan",
      authorImage: "/templates/spaSalon1/images/team-1.jpg",
      category: "Wellness",
      tags: ["spa", "wellness", "relaxation"],
      publishedAt: "2024-03-15",
      featured: true,
      order: 1,
    },
    {
      id: "blog-2",
      slug: "skincare-routine-for-beginners",
      title: "Building the Perfect Skincare Routine",
      excerpt: "Our experts share the essential steps for a skincare routine that will transform your complexion.",
      content: "<p>A good skincare routine is the foundation of healthy, glowing skin...</p>",
      image: "/templates/spaSalon1/images/blog/img-02.jpg",
      author: "Nour Ibrahim",
      authorImage: "/templates/spaSalon1/images/team-3.jpg",
      category: "Skin Care",
      tags: ["skincare", "beauty", "tips"],
      publishedAt: "2024-03-08",
      featured: true,
      order: 2,
    },
    {
      id: "blog-3",
      slug: "hair-care-tips-for-summer",
      title: "Hair Care Tips for the Summer Season",
      excerpt: "Protect and nourish your hair during the hot months with these expert tips from our senior stylist.",
      content: "<p>Summer can be tough on your hair. Here's how to keep it healthy...</p>",
      image: "/templates/spaSalon1/images/blog/img-03.jpg",
      author: "Sara Ali",
      authorImage: "/templates/spaSalon1/images/team-2.jpg",
      category: "Hair",
      tags: ["hair", "summer", "tips"],
      publishedAt: "2024-02-28",
      featured: false,
      order: 3,
    },
  ],
  appointment: {
    enabled: true,
    title: "Book Your Appointment",
    subtitle: "Choose your preferred service and time. We'll confirm within 24 hours.",
    services: [
      "Facial Treatment",
      "Body Massage",
      "Hair Styling",
      "Manicure & Pedicure",
      "Hot Stone Therapy",
      "Aromatherapy",
    ],
    timeSlots: [
      "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM",
      "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM",
      "5:00 PM", "6:00 PM", "7:00 PM",
    ],
    daysOpen: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    note: "Sunday appointments available by special request only.",
  },
  contact: {
    formTitle: "Send Us a Message",
    formSubtitle: "We'd love to hear from you. Fill in the form and we'll get back to you shortly.",
    showMap: true,
    mapEmbedUrl: "https://maps.google.com/maps?q=Cairo,Egypt&output=embed",
    hours: [
      { day: "Monday – Friday", time: "9:00 AM – 8:00 PM" },
      { day: "Saturday", time: "9:00 AM – 6:00 PM" },
      { day: "Sunday", time: "By Appointment Only" },
    ],
  },
  footer: {
    description: "Shata Spa & Salon is Cairo's premier luxury wellness destination, offering world-class spa and beauty treatments in an elegant, serene environment.",
    copyrightText: "© 2024 Shata Spa & Salon. All Rights Reserved.",
    columns: [
      {
        title: "Quick Links",
        links: [
          { label: "About Us", href: "/templates/spa-salon-1/preview/about" },
          { label: "Our Services", href: "/templates/spa-salon-1/preview/services" },
          { label: "Our Team", href: "/templates/spa-salon-1/preview/team" },
          { label: "Gallery", href: "/templates/spa-salon-1/preview/gallery" },
          { label: "Book Appointment", href: "/templates/spa-salon-1/preview/appointment" },
        ],
      },
      {
        title: "Services",
        links: [
          { label: "Facial Treatments", href: "/templates/spa-salon-1/preview/services/facial-treatment" },
          { label: "Body Massage", href: "/templates/spa-salon-1/preview/services/body-massage" },
          { label: "Hair Styling", href: "/templates/spa-salon-1/preview/services/hair-styling" },
          { label: "Nail Care", href: "/templates/spa-salon-1/preview/services/manicure-pedicure" },
          { label: "Pricing Plans", href: "/templates/spa-salon-1/preview/pricing" },
        ],
      },
    ],
    showNewsletter: true,
    newsletterTitle: "Subscribe to Our Newsletter",
    newsletterPlaceholder: "Your email address",
  },
  customPages: [
    {
      id: "page-faqs",
      slug: "faqs",
      title: "Frequently Asked Questions",
      content: "",
      metaDescription: "Find answers to common questions about our spa and salon services.",
    },
    {
      id: "page-gift-cards",
      slug: "gift-cards",
      title: "Gift Cards",
      content: "",
      metaDescription: "Give the gift of relaxation with Shata Spa & Salon gift cards.",
    },
    {
      id: "page-terms",
      slug: "terms",
      title: "Terms & Privacy Policy",
      content: "",
      metaDescription: "Our terms of service and privacy policy.",
    },
  ],
};
