import type { JewelryShop1Config } from "./types";

export const defaultJewelryShop1Config: JewelryShop1Config = {
  brand: {
    name: "Shata Jewelry",
    tagline: "Timeless Elegance",
    logo: "/templates/jewelryShop1/images/logo.png",
  },
  contact: {
    address: "Cairo, Egypt",
    email: "info@shatasolutions.com",
    phone: "+20 100 000 0000",
    fax: "+20 100 000 0001",
  },
  social: {
    facebook: "#",
    twitter: "#",
    instagram: "#",
  },
  hero: {
    slides: [
      { id: "s1", heading: "Back to Dream", image: "http://placehold.it/440x660" },
      { id: "s2", heading: "Pure Elegance", image: "http://placehold.it/440x660" },
      { id: "s3", heading: "Forever Yours", image: "http://placehold.it/440x660" },
    ],
  },
  about: {
    heading: "ABOUT US",
    subtitle: "A Dreamer's Dream",
    description:
      "At Shata Jewelry, we craft timeless pieces that tell your story. Each collection is thoughtfully designed to celebrate the moments that matter most.",
    image: "http://placehold.it/390x330",
    phone: "+20 100 000 0000",
    year: "2025",
  },
  categories: [
    { id: "c1", name: "Rings", slug: "rings", image: "http://placehold.it/480x320", count: 24 },
    { id: "c2", name: "Necklaces", slug: "necklaces", image: "http://placehold.it/480x320", count: 18 },
    { id: "c3", name: "Bracelets", slug: "bracelets", image: "http://placehold.it/480x320", count: 15 },
    { id: "c4", name: "Earrings", slug: "earrings", image: "http://placehold.it/480x320", count: 20 },
    { id: "c5", name: "Pendants", slug: "pendants", image: "http://placehold.it/480x320", count: 12 },
    { id: "c6", name: "Sets", slug: "sets", image: "http://placehold.it/480x320", count: 8 },
  ],
  products: [
    {
      id: "p1",
      name: "Goldtone Bib Necklace",
      slug: "goldtone-bib-necklace",
      price: 120,
      originalPrice: 150,
      image: "http://placehold.it/480x620",
      category: "necklaces",
      featured: true,
      inStock: true,
      likes: 23,
      description: "A stunning goldtone bib necklace for every occasion.",
      sizes: ["One Size"],
      colors: ["Gold", "Silver"],
    },
    {
      id: "p2",
      name: "Kenneth Jay Lane Ring",
      slug: "kenneth-jay-lane-ring",
      price: 230,
      originalPrice: 230,
      image: "/templates/jewelryShop1/images/img02.jpg",
      category: "rings",
      featured: true,
      inStock: true,
      likes: 18,
      description: "Classic ring with a bold statement design.",
      sizes: ["5", "6", "7", "8"],
      colors: ["Gold"],
    },
    {
      id: "p3",
      name: "Lavin Lady Bracelet",
      slug: "lavin-lady-bracelet",
      price: 173,
      originalPrice: 200,
      image: "http://placehold.it/480x620",
      category: "bracelets",
      featured: true,
      inStock: true,
      likes: 31,
      description: "Elegant bracelet from the Lavin Lady collection.",
      sizes: ["S", "M", "L"],
      colors: ["Rose Gold", "Silver"],
    },
    {
      id: "p4",
      name: "Diamond Drop Earrings",
      slug: "diamond-drop-earrings",
      price: 315,
      originalPrice: 380,
      image: "http://placehold.it/480x620",
      category: "earrings",
      featured: false,
      inStock: true,
      likes: 42,
      description: "Delicate diamond drop earrings for a refined look.",
      sizes: ["One Size"],
      colors: ["White Gold"],
    },
    {
      id: "p5",
      name: "Pearl Pendant",
      slug: "pearl-pendant",
      price: 89,
      originalPrice: 89,
      image: "http://placehold.it/480x620",
      category: "pendants",
      featured: false,
      inStock: true,
      likes: 15,
      description: "Timeless pearl pendant on a fine gold chain.",
      sizes: ["One Size"],
      colors: ["Gold", "Silver"],
    },
    {
      id: "p6",
      name: "Emerald Cocktail Ring",
      slug: "emerald-cocktail-ring",
      price: 450,
      originalPrice: 520,
      image: "http://placehold.it/480x620",
      category: "rings",
      featured: false,
      inStock: false,
      likes: 58,
      description: "Bold emerald cocktail ring, a true statement piece.",
      sizes: ["6", "7", "8"],
      colors: ["Yellow Gold"],
    },
  ],
  testimonials: [
    {
      id: "t1",
      name: "Sara M.",
      text: "Absolutely gorgeous pieces — I get compliments every time I wear my Shata Jewelry necklace. The quality is exceptional.",
      image: "http://placehold.it/135x135",
    },
    {
      id: "t2",
      name: "Layla K.",
      text: "Ordered a set for my wedding and couldn't be happier. The craftsmanship is superb and shipping was fast.",
      image: "http://placehold.it/135x135",
    },
    {
      id: "t3",
      name: "Nour A.",
      text: "Beautiful packaging, stunning jewelry, and excellent customer service. Will definitely order again.",
      image: "http://placehold.it/135x135",
    },
  ],
  blog: [
    {
      id: "b1",
      slug: "how-to-care-for-your-jewelry",
      title: "How to Care for Your Jewelry",
      excerpt: "Simple tips to keep your jewelry sparkling for years to come.",
      content: "Proper care and storage are the keys to lasting jewelry beauty...",
      image: "http://placehold.it/770x400",
      date: "January 15, 2025",
      author: "Shata Jewelry",
      category: "Tips & Care",
    },
    {
      id: "b2",
      slug: "spring-collection-2025",
      title: "Spring Collection 2025",
      excerpt: "Discover our newest pieces inspired by nature and renewal.",
      content: "Our Spring 2025 collection draws inspiration from blossoming gardens...",
      image: "http://placehold.it/770x400",
      date: "March 1, 2025",
      author: "Shata Jewelry",
      category: "Collections",
    },
    {
      id: "b3",
      slug: "the-art-of-gifting-jewelry",
      title: "The Art of Gifting Jewelry",
      excerpt: "A guide to choosing the perfect piece for someone special.",
      content: "Jewelry is one of the most personal and meaningful gifts you can give...",
      image: "http://placehold.it/770x400",
      date: "April 20, 2025",
      author: "Shata Jewelry",
      category: "Gifting",
    },
  ],
  instagram: [
    "http://placehold.it/95x70",
    "http://placehold.it/95x70",
    "http://placehold.it/95x70",
    "http://placehold.it/95x70",
    "http://placehold.it/95x70",
    "http://placehold.it/95x70",
    "http://placehold.it/95x70",
    "http://placehold.it/95x70",
  ],
  shipping: {
    freeShippingMin: 500,
    standardRate: 50,
    expressRate: 100,
  },
  footer: {
    description: "Crafting timeless jewelry pieces that celebrate life's most precious moments.",
    copyright: `© ${new Date().getFullYear()} Shata Jewelry. All rights reserved.`,
  },
};
