import type { SiteConfig } from "./types";

const BASE = "/templates/supermarket3";

export const SUPERMARKET3_DEFAULTS: SiteConfig = {
  name: "BlueMart",
  tagline: "Shop Smart, Live Fresh",
  logo: { text: "BlueMart", alt: "BlueMart" },
  theme: {
    primary: "#1D6CE3",
    primaryFg: "#ffffff",
    accent: "#f59e0b",
    background: "#ffffff",
    foreground: "#1f2937",
    muted: "#6b7280",
    surface: "#f0f6ff",
    border: "#dbeafe",
    radius: "sm",
  },
  contact: {
    email: "shop@bluemart.com",
    phone: "+1 (555) 345-6789",
    address: "789 Blue Blvd, Commerce City, CC 30003",
    hours: "Open daily 7am-9pm",
  },
  social: { facebook: "#", twitter: "#", instagram: "#", youtube: "#" },
  announcement: {
    text: "Big Sale ends in 24 hours - up to 40% off everything!",
    active: true,
  },
  sections: [
    { id: "process", label: "Buying Process", active: true },
    { id: "feature-categories", label: "Feature Categories", active: true },
    { id: "category-top", label: "Category Showcase", active: true },
    { id: "popular", label: "Popular Products", active: true },
    { id: "weekly", label: "Weekly Best Sellers", active: true },
    { id: "new-arrivals", label: "New Arrivals", active: true },
    { id: "blog", label: "Blog Posts", active: true },
  ],
  categories: [
    { id: "1", handle: "breakfast-dairy", name: "Breakfast & Dairy", image: `${BASE}/category/01.jpg`, active: true },
    { id: "2", handle: "meats-seafood", name: "Meats & Seafood", image: `${BASE}/category/02.jpg`, active: true },
    { id: "3", handle: "breads-bakery", name: "Breads & Bakery", image: `${BASE}/category/03.jpg`, active: true },
    { id: "4", handle: "chips-snacks", name: "Chips & Snacks", image: `${BASE}/category/04.jpg`, active: true },
    { id: "5", handle: "organic-produce", name: "Organic Produce", image: `${BASE}/category/05.jpg`, active: true },
    { id: "6", handle: "beverages", name: "Beverages", image: `${BASE}/category/06.jpg`, active: true },
    { id: "7", handle: "frozen-foods", name: "Frozen Foods", image: `${BASE}/category/07.jpg`, active: true },
    { id: "8", handle: "grocery-staples", name: "Grocery & Staples", image: `${BASE}/category/08.jpg`, active: true },
  ],
  products: [
    { id: "1", handle: "croissants", name: "Butter Croissants", category: "breads-bakery", images: [`${BASE}/products/01.jpg`], price: 499, unit: "4 pack", badge: "new", featured: true, active: true },
    { id: "2", handle: "skimmed-milk", name: "Organic Skimmed Milk", category: "breakfast-dairy", images: [`${BASE}/products/02.jpg`], price: 249, unit: "1L", badge: "organic", featured: true, active: true },
    { id: "3", handle: "lamb-chops", name: "New Zealand Lamb Chops", category: "meats-seafood", images: [`${BASE}/products/03.jpg`], price: 1699, compareAtPrice: 2099, unit: "500g", badge: "sale", featured: true, active: true },
    { id: "4", handle: "tiger-prawns", name: "Tiger Prawns", category: "meats-seafood", images: [`${BASE}/products/04.jpg`], price: 1299, unit: "300g", badge: "hot", featured: true, active: true },
    { id: "5", handle: "kettle-chips", name: "Sea Salt Kettle Chips", category: "chips-snacks", images: [`${BASE}/products/05.jpg`], price: 349, compareAtPrice: 449, unit: "150g", badge: "sale", featured: false, active: true },
    { id: "6", handle: "oat-milk", name: "Organic Oat Milk", category: "breakfast-dairy", images: [`${BASE}/products/06.jpg`], price: 399, unit: "1L", badge: null, featured: true, active: true },
    { id: "7", handle: "spinach", name: "Baby Spinach", category: "organic-produce", images: [`${BASE}/products/07.jpg`], price: 299, unit: "200g", badge: "organic", featured: true, active: true },
    { id: "8", handle: "elderflower-cordial", name: "Elderflower Cordial", category: "beverages", images: [`${BASE}/products/08.jpg`], price: 549, unit: "500ml", badge: "new", featured: true, active: true },
    { id: "9", handle: "camembert", name: "Camembert Cheese", category: "breakfast-dairy", images: [`${BASE}/products/09.jpg`], price: 699, unit: "250g", badge: null, featured: false, active: true },
    { id: "10", handle: "frozen-stir-fry", name: "Asian Stir-Fry Veg Mix", category: "frozen-foods", images: [`${BASE}/products/10.jpg`], price: 299, unit: "400g", badge: null, featured: false, active: true },
    { id: "11", handle: "penne-rigate", name: "Penne Rigate", category: "grocery-staples", images: [`${BASE}/products/11.jpg`], price: 189, unit: "500g", badge: null, featured: false, active: true },
    { id: "12", handle: "avocado-oil", name: "Cold-Pressed Avocado Oil", category: "grocery-staples", images: [`${BASE}/products/12.jpg`], price: 1299, compareAtPrice: 1599, unit: "500ml", badge: "sale", featured: true, active: true },
    { id: "13", handle: "iced-tea", name: "Peach Iced Tea", category: "beverages", images: [`${BASE}/products/13.jpg`], price: 299, unit: "330ml", badge: "hot", featured: false, active: true },
    { id: "14", handle: "gouda-cheese", name: "Smoked Gouda Cheese", category: "breakfast-dairy", images: [`${BASE}/products/14.jpg`], price: 749, unit: "200g", badge: null, featured: true, active: true },
    { id: "15", handle: "cod-fillet", name: "Icelandic Cod Fillet", category: "meats-seafood", images: [`${BASE}/products/15.jpg`], price: 1199, unit: "400g", badge: "new", featured: false, active: true },
    { id: "16", handle: "popcorn", name: "Salted Popcorn", category: "chips-snacks", images: [`${BASE}/products/16.jpg`], price: 199, unit: "100g", badge: null, featured: false, active: true },
    { id: "17", handle: "raspberries", name: "Fresh Raspberries", category: "organic-produce", images: [`${BASE}/products/17.jpg`], price: 449, unit: "250g", badge: "hot", featured: true, active: true },
    { id: "18", handle: "frozen-chips", name: "Oven Chips", category: "frozen-foods", images: [`${BASE}/products/18.jpg`], price: 299, unit: "700g", badge: null, featured: false, active: true },
    { id: "19", handle: "brown-rice", name: "Whole Grain Brown Rice", category: "grocery-staples", images: [`${BASE}/products/19.jpg`], price: 699, unit: "1kg", badge: null, featured: false, active: true },
    { id: "20", handle: "matcha-latte", name: "Matcha Latte Mix", category: "beverages", images: [`${BASE}/products/20.jpg`], price: 899, compareAtPrice: 1099, unit: "200g", badge: "sale", featured: true, active: true },
  ],
};
