import type { FlowerShop1Config } from "./types";

export const FLOWER_SHOP1_STORAGE_KEY = "shata-flower-shop-1-draft";

export const FLOWER_SHOP1_DEFAULTS: FlowerShop1Config = {
  brand: {
    name: "Shata Flowers",
    tagline: "Fresh flowers, gifts, and floral arrangements for every occasion.",
    email: "hello@shataflowers.com",
    phone: "(212) 555-0191",
    address: "Shata Flowers, New York",
  },
  theme: {
    primary: "#e75480",
    accent: "#f9a8d4",
    background: "#ffffff",
    text: "#1a1a1a",
  },
  header: {
    ctaLabel: "Shop Now",
    ctaHref: "/templates/flower-shop-1/preview/shop",
    nav: [
      { id: "home", label: "Home", href: "/templates/flower-shop-1/preview", enabled: true },
      { id: "shop", label: "Shop", href: "/templates/flower-shop-1/preview/shop", enabled: true },
      { id: "categories", label: "Categories", href: "/templates/flower-shop-1/preview/categories", enabled: true },
      { id: "about", label: "About", href: "/templates/flower-shop-1/preview/about", enabled: true },
      { id: "blog", label: "Blog", href: "/templates/flower-shop-1/preview/blog", enabled: true },
      { id: "contact", label: "Contact", href: "/templates/flower-shop-1/preview/contact", enabled: true },
    ],
  },
  homeSections: [
    { id: "hero", name: "Hero Slider", type: "slider", content: "Main hero banner with featured flower arrangements.", enabled: true },
    { id: "categories", name: "Flower Categories", type: "carousel", content: "Browse categories: bouquets, wreaths, gifts.", enabled: true },
    { id: "featured", name: "Featured Products", type: "products", content: "Top-selling fresh flower arrangements.", enabled: true },
    { id: "banners", name: "Occasion Banners", type: "banners", content: "Valentine's, Mother's Day, Wedding banners.", enabled: true },
    { id: "instagram", name: "Instagram Gallery", type: "gallery", content: "Latest Instagram flower photos.", enabled: true },
    { id: "blog", name: "Blog / News", type: "blog", content: "Flower care tips and occasion guides.", enabled: true },
  ],
  heroBanners: [
    {
      id: "hero-1",
      handle: "fresh-bouquets",
      name: "Fresh Flower Bouquets",
      shortDescription: "Handcrafted fresh bouquets for every occasion.",
      description: "Browse our seasonal selection of fresh-cut flowers and bespoke arrangements.",
      image: "/templates/flowerShop1/assets/img/slider/home1-slide1.jpg",
      badge: "New Arrival",
      enabled: true,
      featured: true,
    },
    {
      id: "hero-2",
      handle: "seasonal-arrangements",
      name: "Seasonal Arrangements",
      shortDescription: "Beautiful seasonal floral arrangements.",
      description: "Stunning arrangements crafted from the finest seasonal blooms.",
      image: "/templates/flowerShop1/assets/img/slider/home1-slide2.jpg",
      badge: "Featured",
      enabled: true,
      featured: true,
    },
  ],
  categories: [
    {
      id: "bouquets",
      handle: "bouquets",
      name: "Bouquets",
      shortDescription: "Fresh hand-tied bouquets.",
      description: "Our signature fresh-cut bouquets in a range of sizes and styles.",
      image: "/templates/flowerShop1/assets/img/banner/banner-1.jpg",
      enabled: true,
      featured: true,
    },
    {
      id: "wreaths",
      handle: "wreaths",
      name: "Wreaths",
      shortDescription: "Elegant floral wreaths.",
      description: "Handcrafted wreaths for doors, events, and memorials.",
      image: "/templates/flowerShop1/assets/img/banner/banner-2.jpg",
      enabled: true,
      featured: true,
    },
    {
      id: "plants",
      handle: "plants",
      name: "Potted Plants",
      shortDescription: "Long-lasting potted plants.",
      description: "Indoor and outdoor potted plants that last beyond a single occasion.",
      image: "/templates/flowerShop1/assets/img/banner/banner-3.jpg",
      enabled: true,
      featured: true,
    },
    {
      id: "gifts",
      handle: "gifts",
      name: "Flower Gifts",
      shortDescription: "Flowers paired with gifts.",
      description: "Curated gift bundles combining fresh flowers with chocolates, candles, and more.",
      image: "/templates/flowerShop1/assets/img/banner/banner-4.jpg",
      enabled: true,
      featured: true,
    },
  ],
  products: [
    {
      id: "rose-bouquet",
      handle: "rose-bouquet",
      name: "Red Rose Bouquet",
      shortDescription: "Classic red roses — the perfect romantic gift.",
      description: "A timeless bouquet of 12 long-stemmed red roses, hand-tied with green foliage.",
      image: "/templates/flowerShop1/assets/img/product/product-1.jpg",
      price: "$45.00",
      category: "bouquets",
      badge: "Bestseller",
      enabled: true,
      featured: true,
    },
    {
      id: "sunflower-bunch",
      handle: "sunflower-bunch",
      name: "Sunflower Bunch",
      shortDescription: "Bright and cheerful sunflowers.",
      description: "A vibrant bunch of fresh sunflowers that bring sunshine to any room.",
      image: "/templates/flowerShop1/assets/img/product/product-2.jpg",
      price: "$32.00",
      category: "bouquets",
      badge: "Popular",
      enabled: true,
      featured: true,
    },
    {
      id: "mixed-spring",
      handle: "mixed-spring",
      name: "Mixed Spring Bouquet",
      shortDescription: "Seasonal spring flowers in full bloom.",
      description: "A beautiful mix of tulips, peonies, and ranunculus in soft spring colours.",
      image: "/templates/flowerShop1/assets/img/product/product-3.jpg",
      price: "$55.00",
      category: "bouquets",
      enabled: true,
      featured: true,
    },
    {
      id: "white-lily",
      handle: "white-lily",
      name: "White Lily Arrangement",
      shortDescription: "Elegant white lilies for formal occasions.",
      description: "Tall, graceful white lilies arranged in a premium glass vase.",
      image: "/templates/flowerShop1/assets/img/product/product-4.jpg",
      price: "$60.00",
      category: "bouquets",
      badge: "New",
      enabled: true,
      featured: true,
    },
    {
      id: "garden-wreath",
      handle: "garden-wreath",
      name: "Garden Wreath",
      shortDescription: "Seasonal garden-style wreath.",
      description: "A lush garden wreath made with eucalyptus, roses, and seasonal blooms.",
      image: "/templates/flowerShop1/assets/img/product/product-5.jpg",
      price: "$75.00",
      category: "wreaths",
      enabled: true,
      featured: false,
    },
    {
      id: "orchid-plant",
      handle: "orchid-plant",
      name: "Phalaenopsis Orchid",
      shortDescription: "Long-lasting indoor orchid.",
      description: "A stunning Phalaenopsis orchid in a decorative ceramic pot — lasts weeks.",
      image: "/templates/flowerShop1/assets/img/product/product-6.jpg",
      price: "$48.00",
      category: "plants",
      enabled: true,
      featured: false,
    },
  ],
  occasions: [
    {
      id: "valentines",
      handle: "valentines",
      name: "Valentine's Day",
      shortDescription: "Romantic roses and heart arrangements.",
      description: "Say it with flowers — our Valentine's collection of roses, tulips, and gift bundles.",
      image: "/templates/flowerShop1/assets/img/banner/banner-5.jpg",
      badge: "Seasonal",
      enabled: true,
      featured: true,
    },
    {
      id: "mothers-day",
      handle: "mothers-day",
      name: "Mother's Day",
      shortDescription: "Beautiful arrangements to celebrate Mum.",
      description: "Spoil mum with our curated Mother's Day bouquets and gift sets.",
      image: "/templates/flowerShop1/assets/img/banner/dddd.jpg",
      badge: "Seasonal",
      enabled: true,
      featured: true,
    },
    {
      id: "wedding",
      handle: "wedding",
      name: "Wedding Flowers",
      shortDescription: "Bridal bouquets and ceremony arrangements.",
      description: "Bespoke wedding flowers — from bridal bouquets to full venue dressing.",
      image: "/templates/flowerShop1/assets/img/banner/img-bottom-menu.jpg",
      enabled: true,
      featured: true,
    },
  ],
  offers: [
    {
      id: "free-delivery",
      handle: "free-delivery",
      name: "Free Delivery Over $60",
      shortDescription: "Order over $60 and get free same-day delivery.",
      description: "We offer free same-day delivery on all orders over $60 within the city.",
      image: "/templates/flowerShop1/assets/img/icon/free_shipping.png",
      badge: "Deal",
      enabled: true,
      featured: true,
    },
    {
      id: "money-back",
      handle: "money-back",
      name: "Freshness Guarantee",
      shortDescription: "Not happy? We'll replace your flowers free.",
      description: "If your flowers aren't fresh, we'll replace them — no questions asked.",
      image: "/templates/flowerShop1/assets/img/icon/money_back.png",
      badge: "Guarantee",
      enabled: true,
      featured: true,
    },
    {
      id: "support",
      handle: "support",
      name: "24/7 Support",
      shortDescription: "We're here whenever you need us.",
      description: "Our floral experts are available around the clock to help you choose the perfect arrangement.",
      image: "/templates/flowerShop1/assets/img/icon/support247.png",
      enabled: true,
      featured: true,
    },
  ],
  testimonials: [
    {
      id: "testimonial-1",
      handle: "testimonial-1",
      name: "Sarah M.",
      shortDescription: "Gorgeous flowers, fast delivery.",
      description: "Ordered a birthday bouquet for my mum and it arrived exactly on time. The flowers were stunning — she was thrilled!",
      image: "/templates/flowerShop1/assets/img/about/avatar.jpg",
      enabled: true,
      featured: true,
    },
    {
      id: "testimonial-2",
      handle: "testimonial-2",
      name: "James R.",
      shortDescription: "Perfect wedding flowers.",
      description: "Shata Flowers handled all the flowers for our wedding. Every arrangement was beyond what we imagined.",
      image: "/templates/flowerShop1/assets/img/about/avatar.jpg",
      enabled: true,
      featured: true,
    },
  ],
  blog: [
    {
      id: "flower-care-tips",
      handle: "flower-care-tips",
      name: "How to Keep Cut Flowers Fresh Longer",
      shortDescription: "Simple tips to extend the life of your bouquet.",
      description: "Trim the stems, change the water daily, and keep flowers away from direct sunlight — learn all our expert tips.",
      image: "/templates/flowerShop1/assets/img/blog/blog-large-4.jpg",
      enabled: true,
      featured: true,
    },
    {
      id: "seasonal-guide",
      handle: "seasonal-guide",
      name: "Seasonal Flower Guide: What's in Bloom",
      shortDescription: "Discover what flowers are in season right now.",
      description: "Shopping in-season flowers means fresher blooms, lower prices, and better sustainability.",
      image: "/templates/flowerShop1/assets/img/blog/blog-large-6.jpg",
      enabled: true,
      featured: true,
    },
    {
      id: "wedding-trends",
      handle: "wedding-trends",
      name: "Top Wedding Flower Trends This Year",
      shortDescription: "From wildflower meadows to architectural blooms.",
      description: "Our florists share the most requested wedding flower styles and how to incorporate them into your big day.",
      image: "/templates/flowerShop1/assets/img/blog/blog-large-7.jpg",
      enabled: true,
      featured: false,
    },
  ],
  pages: [
    { id: "faq", title: "FAQ", slug: "faq", content: "Common questions about ordering, delivery, and our flowers.", enabled: true },
    { id: "delivery", title: "Delivery Information", slug: "delivery", content: "Details on our delivery areas, timings, and costs.", enabled: true },
  ],
  contact: {
    heading: "Contact Shata Flowers",
    formTitle: "Send us a message",
    mapLabel: "Shata Flowers location",
    note: "We respond to all enquiries within 2 hours during business hours.",
  },
  footer: {
    description: "Shata Flowers — fresh flowers, gifts, and bespoke arrangements delivered to your door.",
    copyright: "© 2026 Shata Flowers. All Rights Reserved.",
  },
};
