import type { SiteConfig } from "./types";

const BASE = "/templates/supermarket4";

export const SUPERMARKET4_DEFAULTS: SiteConfig = {
  name: "OrangeMart",
  tagline: "Fresh Deals Every Day",
  logo: { text: "OrangeMart", alt: "OrangeMart" },
  theme: {
    primary: "#EA580C", primaryFg: "#ffffff", accent: "#fbbf24",
    background: "#F3F4F6", foreground: "#1c1917", muted: "#78716c",
    surface: "#ffffff", border: "#e7e5e4", radius: "sm",
  },
  contact: {
    email: "info@orangemart.com",
    phone: "+1 (555) 456-7890",
    address: "321 Orange Lane, Harvest City, HC 40004",
    hours: "Daily 8am–9pm",
  },
  social: { facebook: "#", twitter: "#", instagram: "#", youtube: "#" },
  announcement: { text: "Up to 30% off — this weekend only!", active: true },
  sections: [
    { id: "feature-cats",     label: "Feature Categories",  active: true },
    { id: "best-selling",     label: "Best Selling Products", active: true },
    { id: "featured-discount",label: "Featured Discounts",  active: true },
    { id: "less-discount",    label: "Up to 20% Off",        active: true },
    { id: "less-discount-2",  label: "Up to 40% Off",        active: true },
    { id: "recently-added",   label: "Recently Added",       active: true },
    { id: "blog",             label: "Blog Posts",           active: true },
    { id: "short-service",    label: "Service Strip",        active: true },
  ],
  categories: [
    { id: "1", handle: "breakfast-dairy",  name: "Breakfast & Dairy",  image: `${BASE}/category/01.jpg`, active: true },
    { id: "2", handle: "meats-seafood",    name: "Meats & Seafood",    image: `${BASE}/category/02.jpg`, active: true },
    { id: "3", handle: "breads-bakery",    name: "Breads & Bakery",    image: `${BASE}/category/03.jpg`, active: true },
    { id: "4", handle: "chips-snacks",     name: "Chips & Snacks",     image: `${BASE}/category/04.jpg`, active: true },
    { id: "5", handle: "organic-produce",  name: "Organic Produce",    image: `${BASE}/category/05.jpg`, active: true },
    { id: "6", handle: "beverages",        name: "Beverages",          image: `${BASE}/category/06.jpg`, active: true },
    { id: "7", handle: "frozen-foods",     name: "Frozen Foods",       image: `${BASE}/category/07.jpg`, active: true },
    { id: "8", handle: "grocery-staples",  name: "Grocery & Staples",  image: `${BASE}/category/08.jpg`, active: true },
  ],
  products: [
    { id: "1",  handle: "multigrain-loaf",    name: "Multigrain Loaf",          category: "breads-bakery",    images: [`${BASE}/products/01.jpg`], price:  369, unit: "loaf",   badge: "new",     featured: true,  active: true },
    { id: "2",  handle: "buttermilk",         name: "Fresh Buttermilk",         category: "breakfast-dairy",  images: [`${BASE}/products/02.jpg`], price:  219, unit: "500ml",  badge: null,      featured: false, active: true },
    { id: "3",  handle: "pork-ribs",          name: "BBQ Pork Ribs",            category: "meats-seafood",    images: [`${BASE}/products/03.jpg`], price: 1499, compareAtPrice: 1799, unit: "800g", badge: "sale", featured: true, active: true },
    { id: "4",  handle: "mackerel-fillet",    name: "Smoked Mackerel Fillet",   category: "meats-seafood",    images: [`${BASE}/products/04.jpg`], price:  899, unit: "200g",  badge: "hot",     featured: true,  active: true },
    { id: "5",  handle: "corn-chips",         name: "Tex-Mex Corn Chips",       category: "chips-snacks",     images: [`${BASE}/products/05.jpg`], price:  299, compareAtPrice: 399, unit: "200g", badge: "sale", featured: false, active: true },
    { id: "6",  handle: "double-cream",       name: "Double Cream",             category: "breakfast-dairy",  images: [`${BASE}/products/06.jpg`], price:  329, unit: "300ml",  badge: null,      featured: true,  active: true },
    { id: "7",  handle: "broccoli",           name: "Organic Broccoli",         category: "organic-produce",  images: [`${BASE}/products/07.jpg`], price:  199, unit: "each",   badge: "organic", featured: true,  active: true },
    { id: "8",  handle: "lemonade",           name: "Homestyle Lemonade",       category: "beverages",        images: [`${BASE}/products/08.jpg`], price:  349, unit: "1L",     badge: "new",     featured: true,  active: true },
    { id: "9",  handle: "cream-cheese",       name: "Philadelphia Cream Cheese",category: "breakfast-dairy",  images: [`${BASE}/products/09.jpg`], price:  449, unit: "200g",  badge: null,      featured: false, active: true },
    { id: "10", handle: "hash-browns",        name: "Crispy Hash Browns",       category: "frozen-foods",     images: [`${BASE}/products/10.jpg`], price:  399, unit: "600g",  badge: null,      featured: false, active: true },
    { id: "11", handle: "tagliatelle",        name: "Egg Tagliatelle",          category: "grocery-staples",  images: [`${BASE}/products/11.jpg`], price:  249, unit: "250g",  badge: null,      featured: false, active: true },
    { id: "12", handle: "sesame-oil",         name: "Toasted Sesame Oil",       category: "grocery-staples",  images: [`${BASE}/products/12.jpg`], price:  699, compareAtPrice: 899, unit: "250ml", badge: "sale", featured: true, active: true },
    { id: "13", handle: "ginger-beer",        name: "Spicy Ginger Beer",        category: "beverages",        images: [`${BASE}/products/13.jpg`], price:  259, unit: "330ml",  badge: "hot",     featured: false, active: true },
    { id: "14", handle: "halloumi",           name: "Grilled Halloumi Cheese",  category: "breakfast-dairy",  images: [`${BASE}/products/14.jpg`], price:  599, unit: "225g",  badge: null,      featured: true,  active: true },
    { id: "15", handle: "sword-fish",         name: "Swordfish Steak",          category: "meats-seafood",    images: [`${BASE}/products/15.jpg`], price: 1799, unit: "400g",  badge: "new",     featured: false, active: true },
    { id: "16", handle: "wasabi-peas",        name: "Wasabi Peas",              category: "chips-snacks",     images: [`${BASE}/products/16.jpg`], price:  349, unit: "150g",  badge: null,      featured: false, active: true },
    { id: "17", handle: "mango",              name: "Ripe Alphonso Mangoes",    category: "organic-produce",  images: [`${BASE}/products/17.jpg`], price:  599, unit: "2 pack", badge: "hot",    featured: true,  active: true },
    { id: "18", handle: "frozen-edamame",     name: "Frozen Edamame Beans",     category: "frozen-foods",     images: [`${BASE}/products/18.jpg`], price:  349, unit: "400g",  badge: null,      featured: false, active: true },
    { id: "19", handle: "quinoa",             name: "Organic Quinoa",           category: "grocery-staples",  images: [`${BASE}/products/19.jpg`], price:  999, unit: "500g",  badge: null,      featured: false, active: true },
    { id: "20", handle: "energy-drink",       name: "Natural Energy Drink",     category: "beverages",        images: [`${BASE}/products/20.jpg`], price:  299, compareAtPrice: 379, unit: "250ml", badge: "sale", featured: true, active: true },
  ],
};
