import type { SiteConfig } from "./types";
const BASE = "/templates/supermarket2";
export const SUPERMARKET2_DEFAULTS: SiteConfig = {
  name: "QuickMart",
  tagline: "Fresh Groceries Delivered Fast",
  logo: { text: "QuickMart", alt: "QuickMart" },
  theme: {
    primary: "#DC2626", primaryFg: "#ffffff", accent: "#f59e0b",
    background: "#ffffff", foreground: "#1f2937", muted: "#6b7280",
    surface: "#f9fafb", border: "#e5e7eb", radius: "sm",
  },
  contact: { email: "hello@quickmart.com", phone: "+1 (555) 876-5432", address: "456 Grocery Ave, Market Town, MT 20002", hours: "Mon-Sun 7am-10pm" },
  social: { facebook: "#", twitter: "#", instagram: "#", youtube: "#" },
  announcement: { text: "Flash Sale: 20% off all fresh produce today only!", active: true },
  sections: [
    { id:"categories", label:"Category Pills", active:true },
    { id:"features", label:"Feature Icons", active:true },
    { id:"weekly", label:"Weekly Best Selling", active:true },
    { id:"method", label:"How It Works", active:true },
    { id:"deal", label:"Deal of the Day", active:true },
    { id:"products", label:"Products Grid", active:true },
    { id:"blog", label:"Blog Posts", active:true },
  ],
  categories: [
    { id:"1", handle:"breakfast-dairy", name:"Breakfast & Dairy", image:BASE+"/category/01.jpg", active:true },
    { id:"2", handle:"meats-seafood", name:"Meats & Seafood", image:BASE+"/category/02.jpg", active:true },
    { id:"3", handle:"breads-bakery", name:"Breads & Bakery", image:BASE+"/category/03.jpg", active:true },
    { id:"4", handle:"chips-snacks", name:"Chips & Snacks", image:BASE+"/category/04.jpg", active:true },
    { id:"5", handle:"organic-produce", name:"Organic Produce", image:BASE+"/category/05.jpg", active:true },
    { id:"6", handle:"beverages", name:"Beverages", image:BASE+"/category/06.jpg", active:true },
    { id:"7", handle:"frozen-foods", name:"Frozen Foods", image:BASE+"/category/07.jpg", active:true },
    { id:"8", handle:"grocery-staples", name:"Grocery & Staples", image:BASE+"/category/08.jpg", active:true },
  ],
  products: [
    { id:"1", handle:"whole-grain-bread", name:"Whole Grain Bread", category:"breads-bakery", images:[BASE+"/products/01.jpg"], price:329, unit:"loaf", badge:"new", featured:true, active:true },
    { id:"2", handle:"free-range-eggs", name:"Free Range Eggs", category:"breakfast-dairy", images:[BASE+"/products/02.jpg"], price:499, unit:"12 pack", badge:"organic", featured:true, active:true },
    { id:"3", handle:"beef-mince", name:"Premium Beef Mince", category:"meats-seafood", images:[BASE+"/products/03.jpg"], price:999, compareAtPrice:1299, unit:"500g", badge:"sale", featured:true, active:true },
    { id:"4", handle:"tuna-steak", name:"Fresh Tuna Steak", category:"meats-seafood", images:[BASE+"/products/04.jpg"], price:1399, unit:"300g", badge:"hot", featured:true, active:true },
    { id:"5", handle:"trail-mix", name:"Organic Trail Mix", category:"chips-snacks", images:[BASE+"/products/05.jpg"], price:699, compareAtPrice:899, unit:"250g", badge:"sale", featured:false, active:true },
    { id:"6", handle:"full-cream-milk", name:"Full Cream Milk", category:"breakfast-dairy", images:[BASE+"/products/06.jpg"], price:279, unit:"2L", badge:null, featured:true, active:true },
    { id:"7", handle:"avocados", name:"Ripe Avocados", category:"organic-produce", images:[BASE+"/products/07.jpg"], price:349, unit:"2 pack", badge:"organic", featured:true, active:true },
    { id:"8", handle:"apple-juice", name:"Fresh Apple Juice", category:"beverages", images:[BASE+"/products/08.jpg"], price:449, unit:"1L", badge:"new", featured:true, active:true },
    { id:"9", handle:"butter", name:"Salted Butter", category:"breakfast-dairy", images:[BASE+"/products/09.jpg"], price:399, unit:"250g", badge:null, featured:false, active:true },
    { id:"10", handle:"frozen-peas", name:"Frozen Garden Peas", category:"frozen-foods", images:[BASE+"/products/10.jpg"], price:249, unit:"500g", badge:null, featured:false, active:true },
    { id:"11", handle:"spaghetti", name:"Bronze-Cut Spaghetti", category:"grocery-staples", images:[BASE+"/products/11.jpg"], price:229, unit:"500g", badge:null, featured:false, active:true },
    { id:"12", handle:"coconut-oil", name:"Organic Coconut Oil", category:"grocery-staples", images:[BASE+"/products/12.jpg"], price:1099, compareAtPrice:1399, unit:"500ml", badge:"sale", featured:true, active:true },
    { id:"13", handle:"kombucha", name:"Ginger Kombucha", category:"beverages", images:[BASE+"/products/13.jpg"], price:399, unit:"350ml", badge:"hot", featured:false, active:true },
    { id:"14", handle:"brie-cheese", name:"French Brie Cheese", category:"breakfast-dairy", images:[BASE+"/products/14.jpg"], price:799, unit:"200g", badge:null, featured:true, active:true },
    { id:"15", handle:"king-prawns", name:"Raw King Prawns", category:"meats-seafood", images:[BASE+"/products/15.jpg"], price:1599, unit:"400g", badge:"new", featured:false, active:true },
    { id:"16", handle:"rice-cakes", name:"Lightly Salted Rice Cakes", category:"chips-snacks", images:[BASE+"/products/16.jpg"], price:249, unit:"130g", badge:null, featured:false, active:true },
    { id:"17", handle:"blueberries", name:"Fresh Blueberries", category:"organic-produce", images:[BASE+"/products/17.jpg"], price:499, unit:"300g", badge:"hot", featured:true, active:true },
    { id:"18", handle:"ice-cream", name:"Vanilla Ice Cream", category:"frozen-foods", images:[BASE+"/products/18.jpg"], price:599, unit:"500ml", badge:null, featured:false, active:true },
    { id:"19", handle:"jasmine-rice", name:"Jasmine Rice", category:"grocery-staples", images:[BASE+"/products/19.jpg"], price:799, unit:"1kg", badge:null, featured:false, active:true },
    { id:"20", handle:"cold-brew-coffee", name:"Cold Brew Coffee", category:"beverages", images:[BASE+"/products/20.jpg"], price:699, compareAtPrice:849, unit:"330ml", badge:"sale", featured:true, active:true },
  ],
};
